from pathlib import Path
p=Path('/mnt/data/customerfix/frontend/src/main.jsx')
s=p.read_text()
s=s.replace('{page==="Customers"&&<Customers customers={customers} addCustomer={addCustomer}/>}','{page==="Customers"&&<Customers customers={customers} addCustomer={addCustomer} setCustomers={setCustomers} sales={sales}/>}')
start=s.index('function Customers({customers,addCustomer}){')
end=s.index('function Suppliers(', start)
new=r'''function Customers({customers,addCustomer,setCustomers,sales}){
 const empty={name:"",code:"",taxNumber:"",streetName:"",buildingNumber:"",additionalStreetName:"",plotIdentification:"",district:"",postalCode:"",city:"",state:"",country:"Malaysia",phone:"",email:"",enabled:true,isCustomer:true,isSupplier:false,taxExempt:false,dueDatePeriod:0,discount:0,loyaltyCard:""};
 const [search,setSearch]=useState(""); const [kind,setKind]=useState("All"); const [editing,setEditing]=useState(null); const [form,setForm]=useState(empty); const [tab,setTab]=useState("General");
 const rows=customers.filter(c=>{const q=search.toLowerCase();const text=[c.name,c.code,c.taxNumber,c.phone,c.email,c.city,c.country].join(" ").toLowerCase();const type=kind==="All"||(kind==="Customers"&&c.isCustomer!==false)||(kind==="Suppliers"&&c.isSupplier);return type&&text.includes(q)});
 const openNew=()=>{setForm({...empty});setTab("General");setEditing("new")};
 const openEdit=c=>{setForm({...empty,...c});setTab("General");setEditing(c.id)};
 const update=k=>e=>setForm(f=>({...f,[k]:e.target.type==="checkbox"?e.target.checked:e.target.value}));
 const saveCustomer=e=>{e.preventDefault();if(!form.name.trim())return;let next;if(editing==="new") next=[...customers,{...form,id:uid(),visits:0,spend:0}];else next=customers.map(c=>c.id===editing?{...c,...form}:c);save("customers",next);setCustomers(next);setEditing(null)};
 const remove=id=>{if(id===1)return;const next=customers.filter(c=>c.id!==id);save("customers",next);setCustomers(next);setEditing(null)};
 const exportCsv=()=>{const head=["Code","Name","Tax Number","Phone","Email","Address","Country","Customer","Supplier","Active"];const body=rows.map(c=>[c.code||"",c.name,c.taxNumber||"",c.phone||"",c.email||"",[c.streetName,c.buildingNumber,c.city,c.state,c.postalCode].filter(Boolean).join(" "),c.country||"",c.isCustomer!==false?"Yes":"No",c.isSupplier?"Yes":"No",c.enabled!==false?"Yes":"No"]);const csv=[head,...body].map(r=>r.map(x=>'"'+String(x).replaceAll('"','""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='customers.csv';a.click();URL.revokeObjectURL(a.href)};
 return <section className="customer-master">
  <div className="customer-topbar"><div><div className="eyebrow">CUSTOMERS & SUPPLIERS</div><h2>Customer Master</h2><p>Manage customer records, contact details, discounts, loyalty and payment terms.</p></div><div className="customer-actions"><button onClick={()=>window.location.reload()}>↻ <span>Refresh</span></button><button onClick={openNew}>＋ <span>Add</span></button><button disabled={!editing} onClick={()=>editing&&openEdit(customers.find(c=>c.id===editing))}>✎ <span>Edit</span></button><button disabled={!editing||editing===1} onClick={()=>editing&&remove(editing)}>⌫ <span>Delete</span></button><button onClick={exportCsv}>↓ <span>Export</span></button><button onClick={()=>window.print()}>▣ <span>Print</span></button></div></div>
  <div className="customer-workspace">
   <div className="customer-list-panel"><div className="customer-list-head"><div><b>{rows.length} record(s)</b><small>Customers & suppliers</small></div><select value={kind} onChange={e=>setKind(e.target.value)}><option>All</option><option>Customers</option><option>Suppliers</option></select></div><div className="customer-search"><select><option>Name</option><option>Code</option><option>Phone</option><option>Email</option></select><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search customers & suppliers..."/><span>⌕</span></div><div className="customer-table-wrap"><table className="customer-table"><thead><tr><th>Code</th><th>Name</th><th>Tax number</th><th>Address</th><th>Country</th><th>Phone</th><th>Email</th><th>Status</th></tr></thead><tbody>{rows.map(c=><tr key={c.id} className={editing===c.id?"selected": ""} onClick={()=>setEditing(c.id)} onDoubleClick={()=>openEdit(c)}><td>{c.code||"—"}</td><td><b>{c.name}</b><small>{c.isSupplier?"Customer · Supplier":"Customer"}</small></td><td>{c.taxNumber||"(none)"}</td><td>{[c.streetName,c.buildingNumber,c.city,c.state,c.postalCode].filter(Boolean).join(", ")||"(none)"}</td><td>{c.country||"Malaysia"}</td><td>{c.phone||"(none)"}</td><td>{c.email||"(none)"}</td><td><span className={c.enabled===false?"status off":"status"}>{c.enabled===false?"Inactive":"Active"}</span></td></tr>)}</tbody></table>{!rows.length&&<div className="customer-empty">No customers found.</div>}</div></div>
   <div className="customer-summary"><div className="customer-summary-head"><div><span className="eyebrow">CUSTOMER</span><h3>{editing&&editing!=="new"?customers.find(c=>c.id===editing)?.name||"Customer": "Customer details"}</h3></div><button onClick={openNew}>＋ New</button></div>{editing&&editing!=="new"?<><div className="customer-profile"><div className="customer-avatar">{(customers.find(c=>c.id===editing)?.name||"C").slice(0,1).toUpperCase()}</div><div><b>{customers.find(c=>c.id===editing)?.name}</b><small>{customers.find(c=>c.id===editing)?.email||"No email address"}</small></div></div><div className="customer-stats"><div><b>{customers.find(c=>c.id===editing)?.visits||0}</b><small>Visits</small></div><div><b>{money(customers.find(c=>c.id===editing)?.spend||0)}</b><small>Total spend</small></div><div><b>{customers.find(c=>c.id===editing)?.loyaltyCard||"—"}</b><small>Loyalty card</small></div></div><button className="customer-edit-main" onClick={()=>openEdit(customers.find(c=>c.id===editing))}>Edit customer</button></>:<div className="customer-placeholder">Select a customer from the list or click <b>+ New</b> to create a customer.</div>}</div>
  </div>
  {editing&&<div className="customer-modal-backdrop" onMouseDown={()=>setEditing(null)}><form className="customer-modal" onSubmit={saveCustomer} onMouseDown={e=>e.stopPropagation()}><div className="customer-modal-head"><div><span className="eyebrow">CUSTOMER MASTER</span><h3>{editing==="new"?"New customer / supplier":"Edit customer / supplier"}</h3></div><button type="button" onClick={()=>setEditing(null)}>×</button></div><div className="customer-tabs">{["General","Discounts","Loyalty cards","Payment terms"].map(t=><button type="button" className={tab===t?"active":""} onClick={()=>setTab(t)} key={t}>{t}</button>)}</div><div className="customer-form-body">
   {tab==="General"&&<><div className="customer-form-section"><h4>General information</h4><div className="customer-form-grid"><label>Name*<input value={form.name} onChange={update("name")} autoFocus/></label><label>Code<input value={form.code} onChange={update("code")}/></label><label>Tax number<input value={form.taxNumber} onChange={update("taxNumber")}/></label><label>Country<select value={form.country} onChange={update("country")}><option>Malaysia</option><option>Singapore</option><option>Indonesia</option><option>Thailand</option><option>Other</option></select></label></div></div><div className="customer-form-section"><h4>Address</h4><div className="customer-form-grid"><label>Street name<input value={form.streetName} onChange={update("streetName")}/></label><label>Building number<input value={form.buildingNumber} onChange={update("buildingNumber")}/></label><label>Additional street name<input value={form.additionalStreetName} onChange={update("additionalStreetName")}/></label><label>Plot identification<input value={form.plotIdentification} onChange={update("plotIdentification")}/></label><label>District<input value={form.district} onChange={update("district")}/></label><label>Postcode<input value={form.postalCode} onChange={update("postalCode")}/></label><label>City<input value={form.city} onChange={update("city")}/></label><label>State / Province<input value={form.state} onChange={update("state")}/></label></div></div><div className="customer-form-section"><h4>Contact & status</h4><div className="customer-form-grid"><label>Phone number<input value={form.phone} onChange={update("phone")}/></label><label>Email<input type="email" value={form.email} onChange={update("email")}/></label></div><div className="customer-checks"><label><input type="checkbox" checked={!!form.enabled} onChange={update("enabled")}/> Active</label><label><input type="checkbox" checked={form.isCustomer!==false} onChange={update("isCustomer")}/> Customer</label><label><input type="checkbox" checked={!!form.isSupplier} onChange={update("isSupplier")}/> Supplier</label><label><input type="checkbox" checked={!!form.taxExempt} onChange={update("taxExempt")}/> Tax exempt</label></div></div></>}
   {tab==="Discounts"&&<div className="customer-form-section"><h4>Customer discount</h4><div className="customer-form-grid"><label>Discount (%)<input type="number" min="0" max="100" value={form.discount} onChange={update("discount")}/></label></div><p className="customer-help">Set a customer-specific discount. This can be applied to eligible sales.</p></div>}
   {tab==="Loyalty cards"&&<div className="customer-form-section"><h4>Loyalty cards</h4><div className="customer-form-grid"><label>Card number<input value={form.loyaltyCard} onChange={update("loyaltyCard")} placeholder="Scan or enter card number"/></label></div><p className="customer-help">One customer can have a loyalty card number associated with the account.</p></div>}
   {tab==="Payment terms"&&<div className="customer-form-section"><h4>Payment terms</h4><div className="customer-form-grid"><label>Due date period (days)<input type="number" min="0" value={form.dueDatePeriod} onChange={update("dueDatePeriod")}/></label></div><p className="customer-help">Use 0 for immediate payment. A positive value defines the allowed credit period.</p></div>}
  </div><div className="customer-modal-foot"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button type="submit">Save customer</button></div></form></div>}
 </section>
}
'''
s=s[:start]+new+s[end:]
p.write_text(s)
