server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    location = / {
        return 302 /SP-Manager/;
    }

    location /SP-Manager/ {
        try_files $uri $uri/ /SP-Manager/index.html;
    }
}
