import React,{useMemo,useState}from"react";import{createRoot}from"react-dom/client";import"./styles.css";
const P=[["SP001","Tinted Film Standard","Tinted Film",180,12],["SP002","Tinted Film Premium","Tinted Film",280,8],["SP003","Tinted Film Ceramic","Tinted Film",450,5],["SP004","Front Windscreen Film","Windscreen",160,14],["SP005","Rear Windscreen Film","Windscreen",140,10],["SP006","Door Glass Film","Glass",95,20],["SP007","Security Film","Security",520,4],["SP008","UV Protection Film","Protection",320,9]].map((x,i)=>({id:i+1,code:x[0],name:x[1],group:x[2],price:x[3],stock:x[4],reorder:5}));
const C=[{id:1,name:"Walk-in Customer",phone:"-",email:"-",visits:0,spend:0},{id:2,name:"Ahmad Customer",phone:"012-000 0000",email:"ahmad@example.com",visits:8,spend:2480},{id:3,name:"Corporate Account",phone:"03-0000 0000",email:"sales@example.com",visits:14,spend:5820}];
const nav=["Dashboard","POS / Sales","Products","Inventory","Customers","Suppliers","Purchases","Payments","Refund / Void","Discount / Promotion","Tax","Loyalty","Users & Permissions","Reports","X / Z Report","Named Order / Takeaway","Settings"];
const money=n=>"RM "+Number(n||0).toFixed(2), load=(k,d)=>{try{return JSON.parse(localStorage.getItem("sp_"+k))??d}catch{return d}}, save=(k,v)=>localStorage.setItem("sp_"+k,JSON.stringify(v));
function App(){const[page,setPage]=useState("Dashboard"),[products,setProducts]=useState(()=>load("products",P)),[customers,setCustomers]=useState(()=>load("customers",C)),[sales,setSales]=useState(()=>load("sales",[])),[cart,setCart]=useState([]),[q,setQ]=useState(""),[discount,setDiscount]=useState(0),[payment,setPayment]=useState("Cash"),[customer,setCustomer]=useState(1),[notice,setNotice]=useState("");
const total=cart.reduce((a,x)=>a+x.price*x.qty,0),disc=total*discount/100,grand=total-disc,valid=sales.filter(x=>!x.refunded),today=valid.reduce((a,x)=>a+x.total,0);
const add=p=>setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]);
const sale=()=>{if(!cart.length)return setNotice("Cart masih kosong.");const s={id:Date.now(),no:"INV-"+String(Date.now()).slice(-8),date:new Date().toISOString(),customer,items:cart,subtotal:total,discount:disc,total:grand,payment};save("sales",[...sales,s]);const np=products.map(p=>{const i=cart.find(x=>x.id===p.id);return i?{...p,stock:Math.max(0,p.stock-i.qty)}:p});save("products",np);setProducts(np);setSales([...sales,s]);setCart([]);setDiscount(0);setNotice("Sale berjaya: "+s.no+" — "+money(s.total));setPage("POS / Sales")};
const refund=id=>{const s=sales.find(x=>x.id===id);if(!s||s.refunded)return;const ns=sales.map(x=>x.id===id?{...x,refunded:true}:x);const np=products.map(p=>{const i=s.items.find(x=>x.id===p.id);return i?{...p,stock:p.stock+i.qty}:p});save("sales",ns);save("products",np);setSales(ns);setProducts(np);setNotice("Refund berjaya.")};
const filtered=useMemo(()=>products.filter(p=>(p.name+" "+p.code).toLowerCase().includes(q.toLowerCase())),[products,q]);
return <div className="app"><aside><div className="brand"><b>SP</b><span><strong>SP-Manager</strong><small>Shining Pearl Tinted</small></span></div><label>MODULES</label>{nav.map(n=><button className={page===n?"active":""} onClick={()=>setPage(n)} key={n}>▸ {n}</button>)}</aside><main><header><div><small>SHINING PEARL TINTED</small><h1>{page}</h1></div><span className="online">● Online</span></header>{notice&&<div className="notice">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
{page==="Dashboard"&&<Dashboard sales={valid} total={today} products={products} setPage={setPage}/>}
{page==="POS / Sales"&&<POS filtered={filtered} q={q} setQ={setQ} add={add} cart={cart} setCart={setCart} customers={customers} customer={customer} setCustomer={setCustomer} discount={discount} setDiscount={setDiscount} payment={payment} setPayment={setPayment} total={total} disc={disc} grand={grand} sale={sale}/>}
{page==="Products"&&<Table title="Products" cols={["Code","Product","Group","Price","Stock","Status"]} rows={products.map(p=>[p.code,p.name,p.group,money(p.price),p.stock,p.stock<=p.reorder?"Low":"OK"])}/>}
{page==="Inventory"&&<Table title="Inventory / Stock" cols={["Code","Product","Warehouse","Stock","Reorder","Status"]} rows={products.map(p=>[p.code,p.name,"Main Warehouse",p.stock,p.reorder,p.stock<=p.reorder?"Low":"OK"])}/>}
{page==="Customers"&&<Table title="Customers" cols={["Name","Phone","Email","Visits","Total Spend"]} rows={customers.map(c=>[c.name,c.phone,c.email,c.visits,money(c.spend)])}/>}
{page==="Suppliers"&&<Table title="Suppliers" cols={["Supplier","Contact","Products","Status"]} rows={[["SP Film Supplier","03-1111 2222",6,"Active"],["Auto Glass Trading","03-3333 4444",4,"Active"]]}/>}
{page==="Payments"&&<Table title="Payments" cols={["Document","Date","Type","Amount","Status"]} rows={sales.map(s=>[s.no,new Date(s.date).toLocaleString(),s.payment,money(s.total),s.refunded?"Refunded":"Paid"])}/>}
{page==="Refund / Void"&&<Refund sales={sales} refund={refund}/>}
{page==="Reports"&&<Dashboard sales={valid} total={today} products={products}/>}
{page==="X / Z Report"&&<XZ sales={valid}/>}
{["Purchases","Discount / Promotion","Tax","Loyalty","Users & Permissions","Named Order / Takeaway","Settings"].includes(page)&&<Placeholder title={page}/>}
</main></div>}
function Dashboard({sales,total,products,setPage}){return <section className="content"><div className="hero"><div><small>WELCOME</small><h2>Manage smarter · Sell faster · Grow together</h2><p>SP-Manager web POS test build</p></div>{setPage&&<button onClick={()=>setPage("POS / Sales")}>Open POS</button>}</div><div className="cards"><Card t="Today's Sales" v={money(total)}/><Card t="Transactions" v={sales.length}/><Card t="Average Sale" v={sales.length?money(total/sales.length):money(0)}/><Card t="Low Stock" v={products.filter(p=>p.stock<=p.reorder).length}/></div><div className="panel"><h3>Recent Sales</h3>{sales.slice(-6).reverse().map(s=><div className="row" key={s.id}><span><b>{s.no}</b><small>{new Date(s.date).toLocaleString()}</small></span><strong>{money(s.total)}</strong></div>)}{!sales.length&&<Empty text="Belum ada transaksi. Tekan Open POS untuk test."/ >}</div></section>}
function Card({t,v}){return <div className="card"><small>{t}</small><strong>{v}</strong></div>}
function POS({filtered,q,setQ,add,cart,setCart,customers,customer,setCustomer,discount,setDiscount,payment,setPayment,total,disc,grand,sale}){return <section className="pos"><div className="panel"><input className="search" value={q} onChange={e=>setQ(e.target.value)} placeholder="Scan barcode / search product code or name..."/><div className="products">{filtered.map(p=><button className="product" onClick={()=>add(p)} key={p.id}><small>{p.code}</small><b>{p.name}</b><span>{p.group}</span><strong>{money(p.price)}</strong><em>Stock {p.stock}</em></button>)}</div></div><div className="panel cart"><h3>Current Order</h3><label>Customer</label><select value={customer} onChange={e=>setCustomer(+e.target.value)}>{customers.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select>{cart.map(i=><div className="cartrow" key={i.id}><span><b>{i.name}</b><small>{money(i.price)} × {i.qty}</small></span><div><button onClick={()=>setCart(c=>c.map(x=>x.id===i.id?{...x,qty:x.qty+1}:x))}>+</button><button onClick={()=>setCart(c=>c.flatMap(x=>x.id===i.id?(x.qty>1?[{...x,qty:x.qty-1}]:[]):[x]))}>−</button></div><strong>{money(i.price*i.qty)}</strong></div>)}{!cart.length&&<Empty text="Cart kosong"/>}<label>Discount %</label><input type="number" value={discount} onChange={e=>setDiscount(+e.target.value)} min="0" max="100"/><div className="payments">{["Cash","Card","Online Transfer","QR Payment"].map(x=><button className={payment===x?"sel":""} onClick={()=>setPayment(x)} key={x}>{x}</button>)}</div><div className="totals"><span>Subtotal <b>{money(total)}</b></span><span>Discount <b>- {money(disc)}</b></span><strong>Total <b>{money(grand)}</b></strong></div><button className="complete" onClick={sale}>Complete Sale · {money(grand)}</button></div></section>}
function Table({title,cols,rows}){return <section className="content"><div className="panel"><h3>{title}</h3><div className="table"><table><thead><tr>{cols.map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i}>{r.map((x,j)=><td key={j}>{x}</td>)}</tr>)}</tbody></table></div></div></section>}
function Refund({sales,refund}){return <section className="content"><div className="panel"><h3>Refund / Void</h3>{sales.slice().reverse().map(s=><div className="row" key={s.id}><span><b>{s.no}</b><small>{new Date(s.date).toLocaleString()}</small></span><span><strong>{money(s.total)}</strong>{s.refunded?<i> Refunded</i>:<button onClick={()=>refund(s.id)}>Refund</button>}</span></div>)}{!sales.length&&<Empty text="Tiada transaksi."/ >}</div></section>}
function XZ({sales}){const total=sales.reduce((a,x)=>a+x.total,0);return <section className="content"><div className="cards"><Card t="Transactions" v={sales.length}/><Card t="Gross Sales" v={money(total)}/><Card t="Cash" v={money(sales.filter(x=>x.payment==="Cash").reduce((a,x)=>a+x.total,0))}/><Card t="Card" v={money(sales.filter(x=>x.payment==="Card").reduce((a,x)=>a+x.total,0))}/></div><div className="panel"><h3>X / Z Report</h3><p>Generated from current browser test data.</p></div></section>}
function Placeholder({title}){return <section className="content"><div className="placeholder"><div>◈</div><h2>{title}</h2><p>Module interface is prepared. Full business workflow will be implemented in the next phase.</p></div></section>}
function Empty({text}){return <div className="empty">{text}</div>}
createRoot(document.getElementById("root")).render(<App/>);