<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type, X-SP-Manager-Key');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
function sp_cfg(array $c,string $flat,string $nested,mixed $default=null):mixed{if(array_key_exists($flat,$c))return$c[$flat];if(isset($c['db'])&&is_array($c['db'])&&array_key_exists($nested,$c['db']))return$c['db'][$nested];return$default;}
function sp_body():array{$v=json_decode(file_get_contents('php://input')?:'',true);return is_array($v)?$v:[];}
function sp_outlet(PDO $pdo,string $outlet):int{$outlet=trim($outlet);if($outlet==='')$outlet='SP01';if(ctype_digit($outlet)){$q=$pdo->prepare('SELECT id FROM outlets WHERE id=? AND active=1 LIMIT 1');$q->execute([(int)$outlet]);$id=$q->fetchColumn();if($id!==false)return(int)$id;}$q=$pdo->prepare('SELECT id FROM outlets WHERE outlet_code=? AND active=1 LIMIT 1');$q->execute([$outlet]);$id=$q->fetchColumn();if($id===false)throw new InvalidArgumentException('Outlet not found: '.$outlet);return(int)$id;}
function sp_key(string $key):string{$key=trim($key);if($key===''||strlen($key)>120||!preg_match('/^[A-Za-z0-9._-]+$/',$key))throw new InvalidArgumentException('Invalid state key.');return$key;}
try{
$config=require __DIR__.'/config.php';$host=(string)sp_cfg($config,'db_host','host','localhost');$name=(string)sp_cfg($config,'db_name','name','');$user=(string)sp_cfg($config,'db_user','user','');$pass=(string)sp_cfg($config,'db_pass','pass','');
if($name===''||$user==='')throw new RuntimeException('Database configuration is incomplete.');
$pdo=new PDO('mysql:host='.$host.';dbname='.$name.';charset=utf8mb4',$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);
$pdo->exec("CREATE TABLE IF NOT EXISTS sp_app_state (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,outlet_id BIGINT UNSIGNED NOT NULL,state_key VARCHAR(120) NOT NULL,state_json LONGTEXT NOT NULL,updated_by VARCHAR(120) NULL,created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY uq_sp_app_state_outlet_key(outlet_id,state_key),KEY idx_sp_app_state_outlet_updated(outlet_id,updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
$method=$_SERVER['REQUEST_METHOD'];$action=trim((string)($_GET['action']??''));
if($action==='health'&&$method==='GET'){echo json_encode(['ok'=>true,'service'=>'SP-Manager central state API','database'=>$name,'time'=>date('c')]);exit;}
if($action==='load'&&$method==='GET'){$oid=sp_outlet($pdo,(string)($_GET['outlet']??'SP01'));$q=$pdo->prepare('SELECT state_key,state_json,updated_at FROM sp_app_state WHERE outlet_id=? ORDER BY state_key');$q->execute([$oid]);$data=[];$updated=[];foreach($q->fetchAll() as $row){$data[$row['state_key']]=json_decode((string)$row['state_json'],true);$updated[$row['state_key']]=$row['updated_at'];}echo json_encode(['ok'=>true,'outletId'=>$oid,'data'=>$data,'updatedAt'=>$updated,'count'=>count($data)],JSON_UNESCAPED_SLASHES);exit;}
if(in_array($action,['save','bulk','sync'],true)&&$method==='POST'){
$body=sp_body();$oid=sp_outlet($pdo,(string)($body['outlet']??'SP01'));$updatedBy=trim((string)($body['updatedBy']??''))?:null;
if($action==='save'){$key=sp_key((string)($body['key']??''));$json=json_encode($body['value']??null,JSON_UNESCAPED_SLASHES);if($json===false)throw new RuntimeException('Unable to encode state value.');$q=$pdo->prepare("INSERT INTO sp_app_state(outlet_id,state_key,state_json,updated_by) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE state_json=VALUES(state_json),updated_by=VALUES(updated_by),updated_at=CURRENT_TIMESTAMP");$q->execute([$oid,$key,$json,$updatedBy]);echo json_encode(['ok'=>true,'key'=>$key]);exit;}
$incoming=$body['data']??[];if(!is_array($incoming))$incoming=[];$clean=[];foreach($incoming as $key=>$value){$key=sp_key((string)$key);if(str_starts_with($key,'auto_backup')||str_starts_with($key,'last_backup'))continue;$json=json_encode($value,JSON_UNESCAPED_SLASHES);if($json!==false)$clean[$key]=$json;}
$pdo->beginTransaction();try{$q=$pdo->prepare('SELECT COUNT(*) FROM sp_app_state WHERE outlet_id=?');$q->execute([$oid]);$existing=(int)$q->fetchColumn();if($existing===0&&$clean){$q=$pdo->prepare("INSERT INTO sp_app_state(outlet_id,state_key,state_json,updated_by) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE state_json=VALUES(state_json),updated_by=VALUES(updated_by),updated_at=CURRENT_TIMESTAMP");foreach($clean as $key=>$json)$q->execute([$oid,$key,$json,$updatedBy]);}$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw$e;}
$q=$pdo->prepare('SELECT state_key,state_json,updated_at FROM sp_app_state WHERE outlet_id=? ORDER BY state_key');$q->execute([$oid]);$data=[];$updated=[];foreach($q->fetchAll() as $row){$data[$row['state_key']]=json_decode((string)$row['state_json'],true);$updated[$row['state_key']]=$row['updated_at'];}echo json_encode(['ok'=>true,'mode'=>$existing===0?'initialized-from-browser':'loaded-from-database','outletId'=>$oid,'data'=>$data,'updatedAt'=>$updated,'count'=>count($data)],JSON_UNESCAPED_SLASHES);exit;}
throw new InvalidArgumentException('Route not found.');
}catch(Throwable $e){http_response_code(400);echo json_encode(['ok'=>false,'error'=>$e->getMessage()],JSON_UNESCAPED_SLASHES);}
