<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
header('Access-Control-Allow-Methods: GET, POST, OPTIONS');
if ($_SERVER['REQUEST_METHOD'] === 'OPTIONS') { http_response_code(204); exit; }
$config = require __DIR__ . '/config.php';
try {
  $pdo = new PDO('mysql:host='.($config['db_host'] ?? 'localhost').';dbname='.($config['db_name'] ?? '').';charset=utf8mb4', $config['db_user'] ?? '', $config['db_pass'] ?? '', [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
  $action=trim((string)($_GET['action']??''));
  $json=static function():array{$v=json_decode(file_get_contents('php://input'),true);return is_array($v)?$v:[];};
  $outletId=static function(PDO $pdo,string $v):int{$v=trim($v);if($v==='')throw new InvalidArgumentException('Outlet is required.');if(ctype_digit($v)){$q=$pdo->prepare('SELECT id FROM outlets WHERE id=? AND active=1 LIMIT 1');$q->execute([(int)$v]);$id=$q->fetchColumn();if($id!==false)return(int)$id;}$q=$pdo->prepare('SELECT id FROM outlets WHERE outlet_code=? AND active=1 LIMIT 1');$q->execute([$v]);$id=$q->fetchColumn();if($id===false)throw new InvalidArgumentException('Outlet not found: '.$v);return(int)$id;};
  $read=static function(PDO $pdo,string $display,string $terminal=''){if($display!==''){$q=$pdo->prepare('SELECT d.*,o.outlet_code,o.outlet_name FROM customer_displays d LEFT JOIN outlets o ON o.id=d.outlet_id WHERE d.display_id=? LIMIT 1');$q->execute([$display]);}else{$q=$pdo->prepare('SELECT d.*,o.outlet_code,o.outlet_name FROM customer_displays d LEFT JOIN outlets o ON o.id=d.outlet_id WHERE d.terminal_id=? LIMIT 1');$q->execute([$terminal]);}return$q->fetch()?:null;};
  if($action==='terminals'&&$_SERVER['REQUEST_METHOD']==='GET'){$rows=$pdo->query('SELECT d.id,d.display_id,d.display_name,d.terminal_id,d.enabled,d.state,d.last_seen_at,d.last_connected,d.idle_image_url,o.outlet_code,o.outlet_name FROM customer_displays d LEFT JOIN outlets o ON o.id=d.outlet_id ORDER BY d.display_id')->fetchAll();echo json_encode(['ok'=>true,'data'=>$rows],JSON_UNESCAPED_SLASHES);exit;}
  if($action==='terminal'&&$_SERVER['REQUEST_METHOD']==='POST'){$b=$json();$terminal=trim((string)($b['terminalId']??''));$display=trim((string)($b['displayId']??''));$name=trim((string)($b['displayName']??$display));$enabled=($b['enabled']??true)?1:0;$oid=$outletId($pdo,(string)($b['outletId']??''));if($terminal===''||$display==='')throw new InvalidArgumentException('Terminal ID and Customer Display ID are required.');$q=$pdo->prepare("INSERT INTO customer_displays(outlet_id,display_id,display_name,terminal_id,enabled,state) VALUES(?,?,?,?,?,'IDLE') ON DUPLICATE KEY UPDATE outlet_id=VALUES(outlet_id),display_name=VALUES(display_name),terminal_id=VALUES(terminal_id),enabled=VALUES(enabled),updated_at=NOW()");$q->execute([$oid,$display,$name,$terminal,$enabled]);echo json_encode(['ok'=>true,'data'=>['terminalId'=>$terminal,'displayId'=>$display,'outletId'=>$oid,'enabled'=>$enabled]],JSON_UNESCAPED_SLASHES);exit;}
  if($action==='image'&&$_SERVER['REQUEST_METHOD']==='POST'){$b=$json();$display=trim((string)($b['display_code']??$b['displayId']??''));$img=(string)($b['image_data']??'');if($display==='')throw new InvalidArgumentException('Customer Display ID is required.');if(!preg_match('#^data:image/(png|jpeg|jpg|webp);base64,#i',$img))throw new InvalidArgumentException('A PNG, JPG or WebP image is required.');if(strlen($img)>8*1024*1024)throw new InvalidArgumentException('Image is too large. Maximum 6 MB.');$q=$pdo->prepare('UPDATE customer_displays SET image_data=?,idle_image_url=NULL,updated_at=NOW() WHERE display_id=?');$q->execute([$img,$display]);if($q->rowCount()===0)throw new RuntimeException('Customer Display not found. Save terminal pairing first.');echo json_encode(['ok'=>true]);exit;}
  if($action==='state'&&$_SERVER['REQUEST_METHOD']==='POST'){$b=$json();$display=trim((string)($b['display_code']??$b['displayId']??''));$terminal=trim((string)($b['terminal_id']??$b['terminalId']??''));if($display===''||$terminal==='')throw new InvalidArgumentException('display_code and terminal_id are required.');$state=$b['state']??[];if(!is_array($state))$state=[];$sn=(string)($state['state']??'IDLE');if(!in_array($sn,['IDLE','CART','PAYMENT','COMPLETED','ERROR'],true))$sn='ERROR';$q=$pdo->prepare('SELECT id FROM customer_displays WHERE display_id=? AND terminal_id=? LIMIT 1');$q->execute([$display,$terminal]);$id=$q->fetchColumn();if($id===false)throw new RuntimeException('Customer Display pairing not found. Save terminal pairing first.');$state['updatedAt']=date('c');$q=$pdo->prepare('UPDATE customer_displays SET state=?,state_json=?,last_seen_at=NOW(),last_connected=NOW(),updated_at=NOW() WHERE id=?');$q->execute([$sn,json_encode($state,JSON_UNESCAPED_SLASHES),$id]);echo json_encode(['ok'=>true]);exit;}
  if($action==='state'&&$_SERVER['REQUEST_METHOD']==='GET'){$display=trim((string)($_GET['display']??''));$terminal=trim((string)($_GET['terminal']??''));if($display===''&&$terminal==='')throw new InvalidArgumentException('display or terminal is required.');$row=$read($pdo,$display,$terminal);if(!$row){echo json_encode(['ok'=>true,'data'=>['state'=>'IDLE','items'=>[],'subtotal'=>0,'discount'=>0,'tax'=>0,'total'=>0,'paymentAmount'=>0,'change'=>0,'currency'=>'RM','companyName'=>'Shining Pearl Tinted','imageData'=>'','updatedAt'=>null]]);exit;}$data=json_decode((string)($row['state_json']??''),true);if(!is_array($data))$data=[];$data['state']=$row['state']?:'IDLE';$data['displayName']=$row['display_name'];$data['imageData']=$row['image_data']??'';$data['updatedAt']=$row['updated_at'];$data['companyName']=$data['companyName']??'Shining Pearl Tinted';if(!empty($row['last_seen_at'])&&strtotime($row['last_seen_at'])<time()-15&&$data['state']!=='IDLE')$data['state']='ERROR';echo json_encode(['ok'=>true,'data'=>$data],JSON_UNESCAPED_SLASHES);exit;}
  throw new InvalidArgumentException('Unknown customer display action.');
}catch(Throwable$e){http_response_code(500);echo json_encode(['ok'=>false,'error'=>$e->getMessage()],JSON_UNESCAPED_SLASHES);}
