<?php
declare(strict_types=1);
require_once __DIR__.'/security.php';
header('Content-Type: application/json; charset=utf-8');
if ($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
$c=require __DIR__.'/config.php'; $d=$c['db']??[];
$host=(string)($d['host']??$c['db_host']??'localhost');$port=(string)($d['port']??$c['db_port']??'3306');
$name=(string)($d['name']??$c['db_name']??'');$user=(string)($d['user']??$c['db_user']??'');$pass=(string)($d['pass']??$c['db_pass']??'');
function b():array{$x=json_decode(file_get_contents('php://input')?:'',true);return is_array($x)?$x:[];}
function o(array $x,int $s=200):never{http_response_code($s);echo json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function oid():int{return max(1,(int)($_SERVER['SP_AUTH_OUTLET_ID']??0));}
function uid2():int{return max(0,(int)($_SERVER['SP_AUTH_USER_ID']??0));}
function col(PDO $p,string $t,string $c):bool{$q=$p->prepare('SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=? LIMIT 1');$q->execute([$t,$c]);return(bool)$q->fetchColumn();}
function dt($v):?string{if(!$v)return null;$t=strtotime((string)$v);return$t?date('Y-m-d H:i:s',$t):null;}
function j($v):array{$x=json_decode((string)$v,true);return is_array($x)?$x:[];}
function nextNo(PDO $p,int $out,string $type,string $prefix):string{
 $q=$p->prepare('SELECT id,next_number,prefix FROM document_counters WHERE outlet_id=? AND document_type=? FOR UPDATE');$q->execute([$out,$type]);$r=$q->fetch();
 if(!$r){$p->prepare('INSERT INTO document_counters(outlet_id,document_type,prefix,next_number) VALUES(?,?,?,2)')->execute([$out,$type,$prefix]);$n=1;$pre=$prefix;}
 else{$n=max(1,(int)$r['next_number']);$pre=trim((string)$r['prefix'])?:$prefix;$p->prepare('UPDATE document_counters SET next_number=? WHERE id=?')->execute([$n+1,(int)$r['id']]);}
 return$pre.str_pad((string)$n,8,'0',STR_PAD_LEFT);
}
function snap(PDO $p,$id):array{$id=(int)$id;if(!$id)return[];$q=$p->prepare('SELECT * FROM customers WHERE id=? LIMIT 1');$q->execute([$id]);$r=$q->fetch();if(!$r)return[];return['id'=>(int)$r['id'],'code'=>(string)($r['code']??''),'name'=>(string)($r['name']??''),'phone'=>(string)($r['phone']??''),'email'=>(string)($r['email']??''),'vehicleNumber'=>(string)($r['vehicle_number']??''),'streetName'=>(string)($r['street_name']??''),'buildingNumber'=>(string)($r['building_number']??''),'additionalStreetName'=>(string)($r['additional_street_name']??''),'postalCode'=>(string)($r['postal_code']??''),'city'=>(string)($r['city']??''),'state'=>(string)($r['state']??''),'country'=>(string)($r['country']??'Malaysia')];}
function ni(array $a):array{$z=[];foreach($a as $x){if(!is_array($x))continue;$q=max(0,(float)($x['qty']??$x['quantity']??0));$u=(float)($x['price']??$x['unit_price']??0);$d=(float)($x['discount']??0);$t=(float)($x['tax']??0);$z[]=['product_id'=>(int)($x['productId']??$x['product_id']??$x['id']??0)?:null,'product_name'=>(string)($x['name']??$x['productName']??''),'description'=>(string)($x['description']??''),'quantity'=>$q,'unit_price'=>$u,'discount'=>$d,'tax'=>$t,'line_total'=>(float)($x['lineTotal']??($q*$u-$d+$t)),'warranty_text'=>(string)($x['warrantyText']??(!empty($x['warrantyEnabled'])?'Warranty '.max(1,(int)($x['warrantyYears']??1)).' Year':'')),'maintenance_text'=>(string)($x['maintenanceText']??(!empty($x['maintenanceEnabled'])?'Free Maintenance '.max(1,(int)($x['maintenanceCount']??1)).' x':''))];}return$z;}
function wi(PDO $p,string $type,int $id,array $items):void{$tab=$type==='quotation'?'quotation_items':'invoice_items';$fk=$type==='quotation'?'quotation_id':'invoice_id';$p->prepare("DELETE FROM `$tab` WHERE `$fk`=?")->execute([$id]);$hd=col($p,$tab,'description');$hw=col($p,$tab,'warranty_text');$hm=col($p,$tab,'maintenance_text');foreach(ni($items) as $x){$cs=[$fk,'product_id','product_name'];$vs=[$id,$x['product_id'],$x['product_name']];if($hd){$cs[]='description';$vs[]=$x['description'];}$cs=array_merge($cs,['quantity','unit_price','discount','tax','line_total']);$vs=array_merge($vs,[$x['quantity'],$x['unit_price'],$x['discount'],$x['tax'],$x['line_total']]);if($hw){$cs[]='warranty_text';$vs[]=$x['warranty_text'];}if($hm){$cs[]='maintenance_text';$vs[]=$x['maintenance_text'];}$p->prepare("INSERT INTO `$tab` (`".implode('`,`',$cs)."`) VALUES(".implode(',',array_fill(0,count($cs),'?')).")")->execute($vs);}}
function ri(PDO $p,string $type,int $id):array{$tab=$type==='quotation'?'quotation_items':'invoice_items';$fk=$type==='quotation'?'quotation_id':'invoice_id';$q=$p->prepare("SELECT * FROM `$tab` WHERE `$fk`=? ORDER BY id");$q->execute([$id]);$z=[];foreach($q->fetchAll() as $r)$z[]=['id'=>(int)$r['id'],'productId'=>(int)($r['product_id']??0),'name'=>(string)$r['product_name'],'description'=>(string)($r['description']??''),'qty'=>(float)$r['quantity'],'price'=>(float)$r['unit_price'],'discount'=>(float)$r['discount'],'tax'=>(float)$r['tax'],'lineTotal'=>(float)$r['line_total'],'warrantyText'=>(string)($r['warranty_text']??''),'maintenanceText'=>(string)($r['maintenance_text']??'')];return$z;}
function md(PDO $p,string $type,array $r):array{$qq=$type==='quotation';$m=j($r['data_json']??'');$id=(int)$r['id'];return['id'=>$id,'dbId'=>$id,'documentType'=>$qq?'Quotation':'Invoice','no'=>(string)$r[$qq?'quotation_no':'invoice_no'],'date'=>(string)$r[$qq?'quotation_date':'invoice_date'],'dueDate'=>(string)($r[$qq?'valid_until':'due_date']??''),'customerId'=>(int)($r['customer_id']??0),'quotationId'=>(int)($r['quotation_id']??0),'saleId'=>(int)($r['sale_id']??0),'subtotal'=>(float)$r['subtotal'],'discount'=>(float)$r['discount'],'tax'=>(float)$r['tax'],'total'=>(float)$r['total'],'paymentStatus'=>(string)($r['payment_status']??''),'status'=>(string)$r['status'],'note'=>(string)($r['notes']??''),'paymentMethod'=>(string)($m['paymentMethod']??''),'customer'=>$m['customer']??[],'items'=>ri($p,$type,$id)];}
function ld(PDO $p,string $type,int $out):array{$t=$type==='quotation'?'quotations':'invoices';$q=$p->prepare("SELECT * FROM `$t` WHERE outlet_id=? ORDER BY id DESC LIMIT 1000");$q->execute([$out]);return array_map(fn($r)=>md($p,$type,$r),$q->fetchAll());}
try{
 if(!$name||!$user)throw new RuntimeException('Database configuration is incomplete.');
 $p=new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$out=oid();$a=strtolower(trim((string)($_GET['action']??'')));$x=b();
 if($a==='health')o(['ok'=>true,'api_version'=>'V1']);
 if($a==='list-quotations')o(['ok'=>true,'api_version'=>'V1','documents'=>ld($p,'quotation',$out)]);
 if($a==='list-invoices')o(['ok'=>true,'api_version'=>'V1','documents'=>ld($p,'invoice',$out)]);
 if($a==='save-quotation'||$a==='save-invoice'){
  $type=$a==='save-quotation'?'quotation':'invoice';$tab=$type==='quotation'?'quotations':'invoices';$d=is_array($x['document']??null)?$x['document']:[];$id=(int)($d['dbId']??$d['id']??0);$p->beginTransaction();
  if($id){$q=$p->prepare("SELECT * FROM `$tab` WHERE id=? AND outlet_id=? FOR UPDATE");$q->execute([$id,$out]);$old=$q->fetch();if(!$old)throw new RuntimeException('Document not found.');if($type==='quotation'&&strtoupper((string)$old['status'])==='CONVERTED')throw new RuntimeException('Converted quotation cannot be edited.');}
  $no=trim((string)($d['no']??''));if(!$no||str_contains(strtolower($no),'auto'))$no=nextNo($p,$out,$type==='quotation'?'Quotation':'Invoice',$type==='quotation'?'QT-':'INV-');$cid=(int)($d['customerId']??0)?:null;$meta=json_encode(['customer'=>snap($p,$cid),'paymentMethod'=>(string)($d['paymentMethod']??'')],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
  if($type==='quotation'){$v=[$no,dt($d['date']??null)?:date('Y-m-d H:i:s'),dt($d['dueDate']??null),$cid,(float)($d['subtotal']??0),(float)($d['discount']??0),(float)($d['tax']??0),(float)($d['total']??0),strtoupper((string)($d['status']??'DRAFT')),(string)($d['note']??''),uid2(),$meta];if($id){$p->prepare('UPDATE quotations SET quotation_no=?,quotation_date=?,valid_until=?,customer_id=?,subtotal=?,discount=?,tax=?,total=?,status=?,notes=?,created_by=?,data_json=? WHERE id=? AND outlet_id=?')->execute([...$v,$id,$out]);}else{$p->prepare('INSERT INTO quotations(outlet_id,quotation_no,quotation_date,valid_until,customer_id,subtotal,discount,tax,total,status,notes,created_by,data_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$out,...$v]);$id=(int)$p->lastInsertId();}}
  else{$v=[$no,dt($d['date']??null)?:date('Y-m-d H:i:s'),dt($d['dueDate']??null),$cid,(int)($d['quotationId']??0)?:null,(int)($d['saleId']??0)?:null,(float)($d['subtotal']??0),(float)($d['discount']??0),(float)($d['tax']??0),(float)($d['total']??0),strtoupper((string)($d['paymentStatus']??'UNPAID')),strtoupper((string)($d['status']??'ISSUED')),(string)($d['note']??''),uid2(),$meta];if($id){$p->prepare('UPDATE invoices SET invoice_no=?,invoice_date=?,due_date=?,customer_id=?,quotation_id=?,sale_id=?,subtotal=?,discount=?,tax=?,total=?,payment_status=?,status=?,notes=?,created_by=?,data_json=? WHERE id=? AND outlet_id=?')->execute([...$v,$id,$out]);}else{$p->prepare('INSERT INTO invoices(outlet_id,invoice_no,invoice_date,due_date,customer_id,quotation_id,sale_id,subtotal,discount,tax,total,payment_status,status,notes,created_by,data_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$out,...$v]);$id=(int)$p->lastInsertId();}}
  wi($p,$type,$id,(array)($d['items']??[]));$p->commit();$q=$p->prepare("SELECT * FROM `$tab` WHERE id=?");$q->execute([$id]);o(['ok'=>true,'api_version'=>'V1','document'=>md($p,$type,$q->fetch())]);
 }
 if($a==='convert'){$qid=(int)($x['quotation_id']??0);if(!$qid)throw new InvalidArgumentException('quotation_id is required.');$p->beginTransaction();$q=$p->prepare('SELECT * FROM quotations WHERE id=? AND outlet_id=? FOR UPDATE');$q->execute([$qid,$out]);$r=$q->fetch();if(!$r)throw new RuntimeException('Quotation not found.');$q=$p->prepare('SELECT id FROM invoices WHERE outlet_id=? AND quotation_id=? LIMIT 1');$q->execute([$out,$qid]);if($q->fetchColumn())throw new RuntimeException('This quotation has already been converted to an invoice.');if(strtoupper((string)$r['status'])==='REJECTED')throw new RuntimeException('Rejected quotation cannot be converted.');$no=nextNo($p,$out,'Invoice','INV-');$m=j($r['data_json']??'');$m['convertedFromQuotation']=$r['quotation_no'];$p->prepare('INSERT INTO invoices(outlet_id,invoice_no,invoice_date,due_date,customer_id,quotation_id,subtotal,discount,tax,total,payment_status,status,notes,created_by,data_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$out,$no,date('Y-m-d H:i:s'),dt($x['dueDate']??null),$r['customer_id'],$qid,$r['subtotal'],$r['discount'],$r['tax'],$r['total'],'UNPAID','ISSUED',$r['notes'],uid2(),json_encode($m,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);$iid=(int)$p->lastInsertId();wi($p,'invoice',$iid,ri($p,'quotation',$qid));$p->prepare("UPDATE quotations SET status='CONVERTED' WHERE id=? AND outlet_id=?")->execute([$qid,$out]);$p->commit();$q=$p->prepare('SELECT * FROM invoices WHERE id=?');$q->execute([$iid]);o(['ok'=>true,'api_version'=>'V1','document'=>md($p,'invoice',$q->fetch())]);}
 if($a==='delete-quotation'||$a==='delete-invoice'){$type=$a==='delete-quotation'?'quotation':'invoice';$tab=$type==='quotation'?'quotations':'invoices';$id=(int)($x['id']??0);if(!$id)throw new InvalidArgumentException('id is required.');$p->beginTransaction();$q=$p->prepare("SELECT * FROM `$tab` WHERE id=? AND outlet_id=? FOR UPDATE");$q->execute([$id,$out]);$r=$q->fetch();if(!$r)throw new RuntimeException('Document not found.');if($type==='quotation'&&strtoupper((string)$r['status'])==='CONVERTED')throw new RuntimeException('Converted quotation cannot be deleted.');if($type==='invoice'&&(int)($r['sale_id']??0)>0)throw new RuntimeException('Invoice linked to a sale cannot be deleted.');$ct=$type==='quotation'?'quotation_items':'invoice_items';$fk=$type==='quotation'?'quotation_id':'invoice_id';$p->prepare("DELETE FROM `$ct` WHERE `$fk`=?")->execute([$id]);$p->prepare("DELETE FROM `$tab` WHERE id=? AND outlet_id=?")->execute([$id,$out]);$p->commit();o(['ok'=>true,'api_version'=>'V1']);}
 o(['ok'=>false,'error'=>'Unknown action.'],404);
}catch(Throwable $e){if(isset($p)&&$p instanceof PDO&&$p->inTransaction())$p->rollBack();o(['ok'=>false,'error'=>$e->getMessage()],400);}
