<?php
declare(strict_types=1);
require_once __DIR__.'/security.php';
header('Content-Type: application/json; charset=utf-8');
if ($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
$c=require __DIR__.'/config.php'; $d=$c['db']??[];
$host=(string)($d['host']??$c['db_host']??'localhost');$port=(string)($d['port']??$c['db_port']??'3306');
$name=(string)($d['name']??$c['db_name']??'');$user=(string)($d['user']??$c['db_user']??'');$pass=(string)($d['pass']??$c['db_pass']??'');
function b():array{$x=json_decode(file_get_contents('php://input')?:'',true);return is_array($x)?$x:[];}
function o(array $x,int $s=200):never{http_response_code($s);echo json_encode($x,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}
function oid():int{return max(1,(int)($_SERVER['SP_AUTH_OUTLET_ID']??0));}
function uid2():int{return max(0,(int)($_SERVER['SP_AUTH_USER_ID']??0));}
function col(PDO $p,string $t,string $c):bool{$q=$p->prepare('SELECT 1 FROM information_schema.columns WHERE table_schema=DATABASE() AND table_name=? AND column_name=? LIMIT 1');$q->execute([$t,$c]);return(bool)$q->fetchColumn();}
function tab(PDO $p,string $t):bool{$q=$p->prepare('SELECT 1 FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=? LIMIT 1');$q->execute([$t]);return(bool)$q->fetchColumn();}
function dt($v):?string{return spDateTime($v);}
function j($v):array{$x=json_decode((string)$v,true);return is_array($x)?$x:[];}
function nextNo(PDO $p,int $out,string $type,string $prefix):string {return spNextDocumentNumber($p,$out,$type,$prefix);}
function snap(PDO $p,$id):array{$id=(int)$id;if(!$id)return[];$q=$p->prepare('SELECT * FROM customers WHERE id=? AND (outlet_id=? OR outlet_id IS NULL) LIMIT 1');$q->execute([$id,oid()]);$r=$q->fetch();if(!$r)throw new InvalidArgumentException('Customer not available in this outlet.');return['id'=>(int)$r['id'],'code'=>(string)($r['code']??''),'name'=>(string)($r['name']??''),'phone'=>(string)($r['phone']??''),'email'=>(string)($r['email']??''),'vehicleNumber'=>(string)($r['vehicle_number']??''),'streetName'=>(string)($r['street_name']??''),'buildingNumber'=>(string)($r['building_number']??''),'additionalStreetName'=>(string)($r['additional_street_name']??''),'postalCode'=>(string)($r['postal_code']??''),'city'=>(string)($r['city']??''),'state'=>(string)($r['state']??''),'country'=>(string)($r['country']??'Malaysia')];}
function ni(array $a):array{$z=[];foreach($a as $x){if(!is_array($x))continue;$q=spQuantity($x['qty']??$x['quantity']??0);$u=spMoney($x['price']??$x['unit_price']??0);$d=spMoney($x['discount']??0);$t=spMoney($x['tax']??0);if($d>$q*$u)throw new InvalidArgumentException('Discount exceeds item value.');$z[]=['product_id'=>(int)($x['productId']??$x['product_id']??$x['id']??0)?:null,'product_name'=>(string)($x['name']??$x['productName']??''),'description'=>(string)($x['description']??''),'quantity'=>$q,'unit_price'=>$u,'discount'=>$d,'tax'=>$t,'line_total'=>round($q*$u-$d+$t,2),'warranty_text'=>(string)($x['warrantyText']??(!empty($x['warrantyEnabled'])?'Warranty '.max(1,(int)($x['warrantyYears']??1)).' Year':'')),'maintenance_text'=>(string)($x['maintenanceText']??(!empty($x['maintenanceEnabled'])?'Free Maintenance '.max(1,(int)($x['maintenanceCount']??1)).' x':''))];}return$z;}
function wi(PDO $p,string $type,int $id,array $items):void{$tab=$type==='quotation'?'quotation_items':'invoice_items';$fk=$type==='quotation'?'quotation_id':'invoice_id';$p->prepare("DELETE FROM `$tab` WHERE `$fk`=?")->execute([$id]);$hd=col($p,$tab,'description');$hw=col($p,$tab,'warranty_text');$hm=col($p,$tab,'maintenance_text');foreach(ni($items) as $x){$cs=[$fk,'product_id','product_name'];$vs=[$id,$x['product_id'],$x['product_name']];if($hd){$cs[]='description';$vs[]=$x['description'];}$cs=array_merge($cs,['quantity','unit_price','discount','tax','line_total']);$vs=array_merge($vs,[$x['quantity'],$x['unit_price'],$x['discount'],$x['tax'],$x['line_total']]);if($hw){$cs[]='warranty_text';$vs[]=$x['warranty_text'];}if($hm){$cs[]='maintenance_text';$vs[]=$x['maintenance_text'];}$p->prepare("INSERT INTO `$tab` (`".implode('`,`',$cs)."`) VALUES(".implode(',',array_fill(0,count($cs),'?')).")")->execute($vs);}}
function ri(PDO $p,string $type,int $id):array{$tab=$type==='quotation'?'quotation_items':'invoice_items';$fk=$type==='quotation'?'quotation_id':'invoice_id';$q=$p->prepare("SELECT * FROM `$tab` WHERE `$fk`=? ORDER BY id");$q->execute([$id]);$z=[];foreach($q->fetchAll() as $r)$z[]=['id'=>(int)$r['id'],'productId'=>(int)($r['product_id']??0),'name'=>(string)$r['product_name'],'description'=>(string)($r['description']??''),'qty'=>(float)$r['quantity'],'price'=>(float)$r['unit_price'],'discount'=>(float)$r['discount'],'tax'=>(float)$r['tax'],'lineTotal'=>(float)$r['line_total'],'warrantyText'=>(string)($r['warranty_text']??''),'maintenanceText'=>(string)($r['maintenance_text']??'')];return$z;}
function docPayments(PDO $p,string $type,int $id):array{
 if(!tab($p,'document_payments'))return[];
 $field=$type==='quotation'?'quotation_id':'invoice_id';
 $q=$p->prepare("SELECT id,quotation_id,invoice_id,payment_type_id,payment_type_name,amount,reference_no,notes,paid_at,created_by FROM document_payments WHERE `$field`=? ORDER BY paid_at,id");$q->execute([$id]);$z=[];
 foreach($q->fetchAll() as $r)$z[]=['id'=>(int)$r['id'],'paymentTypeId'=>(int)($r['payment_type_id']??0),'payment'=>(string)($r['payment_type_name']??'Payment'),'amount'=>(float)$r['amount'],'referenceNo'=>(string)($r['reference_no']??''),'notes'=>(string)($r['notes']??''),'paidAt'=>(string)($r['paid_at']??''),'source'=>(!empty($r['quotation_id'])?'deposit':'payment')];
 return$z;
}
function paymentSummary(array $payments,float $total):array{$paid=0.0;foreach($payments as $x)$paid+=(float)($x['amount']??0);$paid=max(0,$paid);$balance=max(0,$total-$paid);$status=$paid<=0?'UNPAID':($balance<=0.00001?'PAID':'PARTIAL');return['paid'=>$paid,'balance'=>$balance,'status'=>$status];}
function addDocPayment(PDO $p,string $type,int $id,int $out,?int $customerId,array $pay):void{
 if(!tab($p,'document_payments'))throw new RuntimeException('Deposit support is not installed. Import QUOTATION-INVOICE-DEPOSIT-MIGRATION-1.0.44.sql into the Central Database.');
 $amount=spMoney($pay['amount']??0,'Payment');if($amount<=0)return;
 $table=$type==='quotation'?'quotations':'invoices';$q=$p->prepare('SELECT * FROM `'.$table.'` WHERE id=? AND outlet_id=? FOR UPDATE');$q->execute([$id,$out]);$doc=$q->fetch();if(!$doc)throw new RuntimeException('Document missing.');if($type==='quotation'&&strtoupper($doc['status'])==='CONVERTED')throw new RuntimeException('Record payment against the converted invoice.');
 $summary=paymentSummary(docPayments($p,$type,$id),(float)$doc['total']);if($amount>$summary['balance']+0.005)throw new InvalidArgumentException('Payment exceeds outstanding balance.');

 $paymentName=trim((string)($pay['payment']??$pay['paymentMethod']??''));if($paymentName==='')$paymentName='Deposit';
 $paymentTypeId=(int)($pay['paymentTypeId']??0)?:null;
 if(!$paymentTypeId&&tab($p,'payment_types')){$q=$p->prepare('SELECT id FROM payment_types WHERE payment_name=? AND enabled=1 ORDER BY CASE WHEN outlet_id=? THEN 0 ELSE 1 END,id LIMIT 1');$q->execute([$paymentName,$out]);$paymentTypeId=(int)($q->fetchColumn()?:0)?:null;}
 if(!$paymentTypeId)throw new InvalidArgumentException('Enabled payment type required.');$q=$p->prepare('SELECT payment_name,mark_paid FROM payment_types WHERE id=? AND enabled=1');$q->execute([$paymentTypeId]);$pt=$q->fetch();if(!$pt||empty($pt['mark_paid']))throw new InvalidArgumentException('Payment method does not record money received.');$paymentName=$pt['payment_name'];
 $quotationId=$type==='quotation'?$id:null;$invoiceId=$type==='invoice'?$id:null;
 $p->prepare('INSERT INTO document_payments(outlet_id,quotation_id,invoice_id,customer_id,payment_type_id,payment_type_name,amount,reference_no,notes,paid_at,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)')->execute([$out,$quotationId,$invoiceId,$customerId,$paymentTypeId,$paymentName,$amount,trim((string)($pay['referenceNo']??''))?:null,trim((string)($pay['notes']??''))?:null,dt($pay['paidAt']??null)?:date('Y-m-d H:i:s'),uid2()?:null]);
}
function md(PDO $p,string $type,array $r):array{$qq=$type==='quotation';$m=j($r['data_json']??'');$id=(int)$r['id'];$payments=docPayments($p,$type,$id);$sum=paymentSummary($payments,(float)$r['total']);$paymentStatus=$qq?$sum['status']:(string)($r['payment_status']??$sum['status']);if($payments)$paymentStatus=$sum['status'];return['id'=>$id,'dbId'=>$id,'documentType'=>$qq?'Quotation':'Invoice','no'=>(string)$r[$qq?'quotation_no':'invoice_no'],'date'=>(string)$r[$qq?'quotation_date':'invoice_date'],'dueDate'=>(string)($r[$qq?'valid_until':'due_date']??''),'customerId'=>(int)($r['customer_id']??0),'quotationId'=>(int)($r['quotation_id']??0),'saleId'=>(int)($r['sale_id']??0),'subtotal'=>(float)$r['subtotal'],'discount'=>(float)$r['discount'],'tax'=>(float)$r['tax'],'total'=>(float)$r['total'],'paidAmount'=>(float)$sum['paid'],'balanceDue'=>(float)$sum['balance'],'payments'=>$payments,'paymentStatus'=>$paymentStatus,'status'=>(string)$r['status'],'note'=>(string)($r['notes']??''),'paymentMethod'=>(string)($m['paymentMethod']??($payments[0]['payment']??'')),'customer'=>$m['customer']??[],'items'=>ri($p,$type,$id)];}
function ld(PDO $p,string $type,int $out):array{$t=$type==='quotation'?'quotations':'invoices';$q=$p->prepare("SELECT * FROM `$t` WHERE outlet_id=? ORDER BY id DESC LIMIT 1000");$q->execute([$out]);return array_map(fn($r)=>md($p,$type,$r),$q->fetchAll());}
try{
 if(!$name||!$user)throw new RuntimeException('Database configuration is incomplete.');
 $p=spApiDatabase();$out=oid();$a=strtolower(trim((string)($_GET['action']??'')));$x=b();
 if($a==='health')o(['ok'=>true,'api_version'=>'V1']);
 if($a==='list-quotations')o(['ok'=>true,'api_version'=>'V1','documents'=>ld($p,'quotation',$out)]);
 if($a==='list-invoices')o(['ok'=>true,'api_version'=>'V1','documents'=>ld($p,'invoice',$out)]);
 if($a==='save-quotation'||$a==='save-invoice'){
  $type=$a==='save-quotation'?'quotation':'invoice';$tab=$type==='quotation'?'quotations':'invoices';$d=is_array($x['document']??null)?$x['document']:[];$id=(int)($d['dbId']??$d['id']??0);$p->beginTransaction();spLockOutlet($p,$out);$rk=spRequestKey($x,'document:'.$a);$replay=spRequestReplay($p,$rk,$x);if($replay){$p->commit();o($replay);}
  if($id){$q=$p->prepare("SELECT * FROM `$tab` WHERE id=? AND outlet_id=? FOR UPDATE");$q->execute([$id,$out]);$old=$q->fetch();if(!$old)throw new RuntimeException('Document not found.');if($type==='quotation'&&strtoupper((string)$old['status'])==='CONVERTED')throw new RuntimeException('Converted quotation cannot be edited.');}
  $lines=ni((array)($d['items']??[]));if(!$lines)throw new InvalidArgumentException('Document items required.');$subtotal=array_sum(array_map(fn($i)=>round($i['quantity']*$i['unit_price'],2),$lines));$discount=spMoney($d['discount']??0);$tax=spMoney($d['tax']??0);$expected=round(array_sum(array_column($lines,'line_total'))-$discount+$tax,2);if($expected<0||abs(spMoney($d['total']??0)-$expected)>0.01)throw new InvalidArgumentException('Document total does not match rows.');$d['subtotal']=$subtotal;$d['total']=$expected;$paidSummary=paymentSummary($id?docPayments($p,$type,$id):[],$expected);if($paidSummary['paid']>$expected+0.005)throw new RuntimeException('Document total cannot be less than money already received.');$d['paymentStatus']=$paidSummary['status'];if($type==='invoice'){if(!$id&&(!empty($d['quotationId'])||!empty($d['saleId'])))throw new RuntimeException('Use the conversion workflow for linked invoices.');if($id){$d['quotationId']=$old['quotation_id'];$d['saleId']=$old['sale_id'];}}
  $no=trim((string)($d['no']??''));if(!$no||str_contains(strtolower($no),'auto'))$no=nextNo($p,$out,$type==='quotation'?'Quotation':'Invoice',$type==='quotation'?'QT-':'INV-');$cid=(int)($d['customerId']??0)?:null;$meta=json_encode(['customer'=>snap($p,$cid),'paymentMethod'=>(string)($d['paymentMethod']??'')],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);
  if($type==='quotation'){
   $cols=['outlet_id','quotation_no','quotation_date'];$vals=[$out,$no,dt($d['date']??null)?:date('Y-m-d H:i:s')];
   if(col($p,'quotations','valid_until')){$cols[]='valid_until';$vals[]=dt($d['dueDate']??null);}
   $cols=array_merge($cols,['customer_id','subtotal','discount','tax','total','status','notes','created_by']);$vals=array_merge($vals,[$cid,(float)($d['subtotal']??0),(float)($d['discount']??0),(float)($d['tax']??0),(float)($d['total']??0),strtoupper((string)($d['status']??'DRAFT')),(string)($d['note']??''),uid2()?:null]);
   if(col($p,'quotations','data_json')){$cols[]='data_json';$vals[]=$meta;}
   if($id){$set=[];foreach(array_slice($cols,1) as $c)$set[]='`'.$c.'`=?';$updateVals=array_slice($vals,1);$updateVals[]=$id;$updateVals[]=$out;$p->prepare('UPDATE quotations SET '.implode(',',$set).' WHERE id=? AND outlet_id=?')->execute($updateVals);}else{$p->prepare('INSERT INTO quotations (`'.implode('`,`',$cols).'`) VALUES('.implode(',',array_fill(0,count($cols),'?')).')')->execute($vals);$id=(int)$p->lastInsertId();}
  } else {
   $cols=['outlet_id','invoice_no','invoice_date','due_date','customer_id','quotation_id','sale_id','subtotal','discount','tax','total','payment_status','status','notes','created_by'];$vals=[$out,$no,dt($d['date']??null)?:date('Y-m-d H:i:s'),dt($d['dueDate']??null),$cid,(int)($d['quotationId']??0)?:null,(int)($d['saleId']??0)?:null,(float)($d['subtotal']??0),(float)($d['discount']??0),(float)($d['tax']??0),(float)($d['total']??0),strtoupper((string)($d['paymentStatus']??'UNPAID')),strtoupper((string)($d['status']??'ISSUED')),(string)($d['note']??''),uid2()?:null];
   if(col($p,'invoices','data_json')){$cols[]='data_json';$vals[]=$meta;}
   if($id){$set=[];foreach(array_slice($cols,1) as $c)$set[]='`'.$c.'`=?';$updateVals=array_slice($vals,1);$updateVals[]=$id;$updateVals[]=$out;$p->prepare('UPDATE invoices SET '.implode(',',$set).' WHERE id=? AND outlet_id=?')->execute($updateVals);}else{$p->prepare('INSERT INTO invoices (`'.implode('`,`',$cols).'`) VALUES('.implode(',',array_fill(0,count($cols),'?')).')')->execute($vals);$id=(int)$p->lastInsertId();}
  }
  wi($p,$type,$id,(array)($d['items']??[]));if(is_array($d['newPayment']??null)&&((float)($d['newPayment']['amount']??0))>0)addDocPayment($p,$type,$id,$out,$cid,$d['newPayment']);$q=$p->prepare("SELECT * FROM `$tab` WHERE id=?");$q->execute([$id]);$response=['ok'=>true,'api_version'=>'V1','document'=>md($p,$type,$q->fetch())];if($type==='invoice'){$paymentSummary=paymentSummary(docPayments($p,$type,$id),$expected);$p->prepare('UPDATE invoices SET payment_status=? WHERE id=? AND outlet_id=?')->execute([$paymentSummary['status'],$id,$out]);}spAudit($p,'DOCUMENT_SAVE',$tab,$id);spRequestComplete($p,$rk,$response);$p->commit();o($response);
 }
 if($a==='convert'){$qid=(int)($x['quotation_id']??0);if(!$qid)throw new InvalidArgumentException('quotation_id is required.');$p->beginTransaction();spLockOutlet($p,$out);$rk=spRequestKey($x,'document:'.$a);$replay=spRequestReplay($p,$rk,$x);if($replay){$p->commit();o($replay);}$q=$p->prepare('SELECT * FROM quotations WHERE id=? AND outlet_id=? FOR UPDATE');$q->execute([$qid,$out]);$r=$q->fetch();if(!$r)throw new RuntimeException('Quotation not found.');$q=$p->prepare('SELECT id FROM invoices WHERE outlet_id=? AND quotation_id=? LIMIT 1');$q->execute([$out,$qid]);if($q->fetchColumn())throw new RuntimeException('This quotation has already been converted to an invoice.');if(strtoupper((string)$r['status'])==='REJECTED')throw new RuntimeException('Rejected quotation cannot be converted.');$no=nextNo($p,$out,'Invoice','INV-');$m=j($r['data_json']??'');$m['convertedFromQuotation']=$r['quotation_no'];$ic=['outlet_id','invoice_no','invoice_date','due_date','customer_id','quotation_id','subtotal','discount','tax','total','payment_status','status','notes','created_by'];$iv=[$out,$no,date('Y-m-d H:i:s'),dt($x['dueDate']??null),$r['customer_id'],$qid,$r['subtotal'],$r['discount'],$r['tax'],$r['total'],'UNPAID','ISSUED',$r['notes'],uid2()?:null];if(col($p,'invoices','data_json')){$ic[]='data_json';$iv[]=json_encode($m,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}$p->prepare('INSERT INTO invoices (`'.implode('`,`',$ic).'`) VALUES('.implode(',',array_fill(0,count($ic),'?')).')')->execute($iv);$iid=(int)$p->lastInsertId();wi($p,'invoice',$iid,ri($p,'quotation',$qid));if(tab($p,'document_payments'))$p->prepare('UPDATE document_payments SET invoice_id=? WHERE quotation_id=? AND outlet_id=?')->execute([$iid,$qid,$out]);$ps=docPayments($p,'invoice',$iid);$sum=paymentSummary($ps,(float)$r['total']);$p->prepare('UPDATE invoices SET payment_status=? WHERE id=? AND outlet_id=?')->execute([$sum['status'],$iid,$out]);$p->prepare("UPDATE quotations SET status='CONVERTED' WHERE id=? AND outlet_id=?")->execute([$qid,$out]);$q=$p->prepare('SELECT * FROM invoices WHERE id=?');$q->execute([$iid]);$response=['ok'=>true,'api_version'=>'V1','document'=>md($p,'invoice',$q->fetch())];spAudit($p,'QUOTATION_CONVERT','invoices',$iid);spRequestComplete($p,$rk,$response);$p->commit();o($response);}
 if($a==='record-payment'){$type=strtolower((string)($x['document_type']??''));if(!in_array($type,['quotation','invoice'],true))throw new InvalidArgumentException('document_type is required.');$id=(int)($x['document_id']??0);if(!$id)throw new InvalidArgumentException('document_id is required.');$tabn=$type==='quotation'?'quotations':'invoices';$p->beginTransaction();spLockOutlet($p,$out);$rk=spRequestKey($x,'document:'.$a);$replay=spRequestReplay($p,$rk,$x);if($replay){$p->commit();o($replay);}$q=$p->prepare("SELECT * FROM `$tabn` WHERE id=? AND outlet_id=? FOR UPDATE");$q->execute([$id,$out]);$r=$q->fetch();if(!$r)throw new RuntimeException('Document not found.');$cid=(int)($r['customer_id']??0)?:null;addDocPayment($p,$type,$id,$out,$cid,is_array($x['payment']??null)?$x['payment']:[]);if($type==='invoice'){$ps=docPayments($p,'invoice',$id);$sum=paymentSummary($ps,(float)$r['total']);$p->prepare('UPDATE invoices SET payment_status=? WHERE id=? AND outlet_id=?')->execute([$sum['status'],$id,$out]);}$q=$p->prepare("SELECT * FROM `$tabn` WHERE id=?");$q->execute([$id]);$response=['ok'=>true,'api_version'=>'V1','document'=>md($p,$type,$q->fetch())];spAudit($p,'DOCUMENT_PAYMENT',$tabn,$id);spRequestComplete($p,$rk,$response);$p->commit();o($response);}
 if($a==='delete-quotation'||$a==='delete-invoice'){$type=$a==='delete-quotation'?'quotation':'invoice';$tab=$type==='quotation'?'quotations':'invoices';$id=(int)($x['id']??0);if(!$id)throw new InvalidArgumentException('id is required.');$p->beginTransaction();spLockOutlet($p,$out);$rk=spRequestKey($x,'document:'.$a);$replay=spRequestReplay($p,$rk,$x);if($replay){$p->commit();o($replay);}$q=$p->prepare("SELECT * FROM `$tab` WHERE id=? AND outlet_id=? FOR UPDATE");$q->execute([$id,$out]);$r=$q->fetch();if(!$r)throw new RuntimeException('Document not found.');if($type==='quotation'&&strtoupper((string)$r['status'])==='CONVERTED')throw new RuntimeException('Converted quotation cannot be deleted.');if($type==='invoice'&&(int)($r['sale_id']??0)>0)throw new RuntimeException('Invoice linked to a sale cannot be deleted.');if(tab($p,'document_payments')){$pf=$type==='quotation'?'quotation_id':'invoice_id';$pq=$p->prepare("SELECT COUNT(*) FROM document_payments WHERE `$pf`=?");$pq->execute([$id]);if((int)$pq->fetchColumn()>0)throw new RuntimeException('Document with a recorded payment cannot be deleted.');}$ct=$type==='quotation'?'quotation_items':'invoice_items';$fk=$type==='quotation'?'quotation_id':'invoice_id';$p->prepare("DELETE FROM `$ct` WHERE `$fk`=?")->execute([$id]);$p->prepare("DELETE FROM `$tab` WHERE id=? AND outlet_id=?")->execute([$id,$out]);$response=['ok'=>true,'api_version'=>'V1'];spAudit($p,'DOCUMENT_DELETE',$tab,$id);spRequestComplete($p,$rk,$response);$p->commit();o($response);}
 o(['ok'=>false,'error'=>'Unknown action.'],404);
}catch(Throwable $e){if(isset($p)&&$p instanceof PDO&&$p->inTransaction())$p->rollBack();o(['ok'=>false,'error'=>$e->getMessage()],400);}
