<?php
declare(strict_types=1);
/** Server-rendered receipt PDF; no browser/Agent receives SMTP credentials. */
function spReceiptPdf(array $company,array $sale,array $customer,array $items,float $paid):string {
 $lines=[(string)($company['company_name']??'SP-Manager'),'Invoice: '.$sale['sale_no'],'Date (UTC): '.$sale['sale_date'],'Customer: '.($customer['name']??'Walk-in customer'),''];
 foreach($items as $n=>$item){$name=(string)$item['product_name'];foreach(str_split($name,85) as $part)$lines[]=$part;$lines[]=sprintf('  Qty %.3f   Unit %.2f   Discount %.2f   Tax %.2f   Amount %.2f',(float)$item['quantity'],(float)$item['unit_price'],(float)$item['discount'],(float)$item['tax'],(float)$item['line_total']);if(!empty($item['warranty_enabled']))$lines[]='  Warranty '.(int)$item['warranty_years'].' Year';if(!empty($item['maintenance_enabled']))$lines[]='  Free Maintenance '.(int)$item['maintenance_count'].' x';$lines[]='';}
 $lines[]='Subtotal: MYR '.number_format((float)$sale['subtotal'],2);$lines[]='Discount: MYR '.number_format((float)$sale['discount'],2);$lines[]='Tax: MYR '.number_format((float)$sale['tax'],2);$lines[]='Total: MYR '.number_format((float)$sale['total'],2);$lines[]='Paid: MYR '.number_format($paid,2);$lines[]='Balance: MYR '.number_format(max(0,(float)$sale['total']-$paid),2);$lines[]='Status: '.$sale['status'];
 $pages=array_chunk($lines,50);$objects=[1=>'<< /Type /Catalog /Pages 2 0 R >>',3=>'<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica /Encoding /WinAnsiEncoding >>'];$kids=[];
 foreach($pages as $n=>$page){$pageId=4+$n*2;$streamId=$pageId+1;$kids[]=$pageId.' 0 R';$text="BT\n/F1 9 Tf\n40 800 Td\n14 TL\n";foreach($page as $line){$encoded=iconv('UTF-8','Windows-1252//TRANSLIT',(string)$line);if($encoded===false)$encoded='[Unsupported text]';$encoded=str_replace(['\\','(',')',"\r","\n"],['\\\\','\\(','\\)',' ',' '],$encoded);$text.='('.$encoded.") Tj\nT*\n";}$text.="ET\n";$objects[$pageId]='<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Resources << /Font << /F1 3 0 R >> >> /Contents '.$streamId.' 0 R >>';$objects[$streamId]='<< /Length '.strlen($text).">>\nstream\n".$text.'endstream';}
 $objects[2]='<< /Type /Pages /Kids ['.implode(' ',$kids).'] /Count '.count($pages).' >>';ksort($objects);$pdf="%PDF-1.4\n%\xE2\xE3\xCF\xD3\n";$offsets=[0=>0];foreach($objects as $id=>$object){$offsets[$id]=strlen($pdf);$pdf.=$id." 0 obj\n".$object."\nendobj\n";}$xref=strlen($pdf);$size=count($objects)+1;$pdf.="xref\n0 ".$size."\n0000000000 65535 f \n";for($i=1;$i<$size;$i++)$pdf.=sprintf("%010d 00000 n \n",$offsets[$i]);$pdf.='trailer << /Size '.$size." /Root 1 0 R >>\nstartxref\n".$xref."\n%%EOF\n";return$pdf;
}
