<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
header('Access-Control-Allow-Methods: GET, OPTIONS');
header('X-SP-Manager-DB-Version: V10');
if ($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
$config=require __DIR__.'/config.php';
$db=$config['db']??null;$host=(string)($db['host']??$config['db_host']??'localhost');$port=(string)($db['port']??$config['db_port']??'3306');$name=(string)($db['name']??$config['db_name']??'');$user=(string)($db['user']??$config['db_user']??'');$pass=(string)($db['pass']??$config['db_pass']??'');
function cols(PDO $pdo,string $table):array{$q=$pdo->query('DESCRIBE `'.str_replace('`','``',$table).'`');$o=[];foreach($q->fetchAll() as $r){$o[(string)$r['Field']]=$r;}return $o;}
function tableExists(PDO $pdo,string $table):bool{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$q->execute([$table]);return(int)$q->fetchColumn()>0;}
function val(array $r,array $keys,$default=null){foreach($keys as $k)if(array_key_exists($k,$r)&&$r[$k]!==null)return $r[$k];return $default;}
function dt($v){if($v===null||$v==='')return null;$t=strtotime(str_replace('T',' ',(string)$v));return $t===false?(string)$v:date('c',$t);}
function outletId(PDO $pdo,string $outlet):int{$outlet=trim($outlet?:'SP01');if(ctype_digit($outlet)){$q=$pdo->prepare('SELECT id FROM outlets WHERE id=? AND active=1 LIMIT 1');$q->execute([(int)$outlet]);}else{$q=$pdo->prepare('SELECT id FROM outlets WHERE outlet_code=? AND active=1 LIMIT 1');$q->execute([$outlet]);}$id=(int)($q->fetchColumn()?:0);if(!$id)throw new RuntimeException('Outlet not found: '.$outlet);return$id;}
function rows(PDO $pdo,string $table,int $oid):array{if(!tableExists($pdo,$table))return[];$s=cols($pdo,$table);$sql='SELECT * FROM `'.$table.'`';$args=[];if(isset($s['outlet_id'])){$sql.=' WHERE outlet_id=?';$args[]=$oid;}$sql.=' ORDER BY id ASC';$q=$pdo->prepare($sql);$q->execute($args);return$q->fetchAll();}
function childRows(PDO $pdo,string $table,string $fk,int $id):array{if(!tableExists($pdo,$table))return[];$s=cols($pdo,$table);if(!isset($s[$fk]))return[];$q=$pdo->prepare('SELECT * FROM `'.$table.'` WHERE `'.$fk.'`=? ORDER BY id ASC');$q->execute([$id]);return$q->fetchAll();}
function mapSale(PDO $pdo,array $r):array{$s=['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'no'=>(string)val($r,['sale_no','invoice_no','number'],''),'orderNumber'=>(string)val($r,['order_number','orderNumber'],''),'date'=>dt(val($r,['sale_date','created_at'])), 'customerId'=>(string)val($r,['customer_id'],''),'orderName'=>(string)val($r,['order_name'],''),'serviceType'=>(string)val($r,['service_type'],''),'subtotal'=>(float)val($r,['subtotal'],0),'discount'=>(float)val($r,['discount'],0),'tax'=>(float)val($r,['tax'],0),'total'=>(float)val($r,['total'],0),'paymentStatus'=>(string)val($r,['payment_status'],''),'status'=>(string)val($r,['status'],'COMPLETED'),'createdBy'=>val($r,['created_by'],''),'note'=>(string)val($r,['notes','note'],''),'internalNote'=>'','voided'=>strtolower((string)val($r,['voided'],0))==='1'||strtolower((string)val($r,['status'],''))==='voided','refunded'=>strtolower((string)val($r,['refunded'],0))==='1'||strtolower((string)val($r,['status'],''))==='refunded','items'=>[],'payments'=>[]];foreach(childRows($pdo,'sale_items','sale_id',(int)$r['id']) as $i)$s['items'][]=['id'=>(int)val($i,['product_id','id']), 'productId'=>(int)val($i,['product_id'],0),'name'=>(string)val($i,['product_name','name'],''),'barcode'=>(string)val($i,['barcode'],''),'qty'=>(float)val($i,['quantity','qty'],0),'price'=>(float)val($i,['unit_price','price'],0),'discount'=>(float)val($i,['discount'],0),'tax'=>(float)val($i,['tax'],0),'total'=>(float)val($i,['line_total','total'],0)];foreach(childRows($pdo,'sale_payments','sale_id',(int)$r['id']) as $p)$s['payments'][]=['paymentTypeId'=>(int)val($p,['payment_type_id'],0),'payment'=>(string)val($p,['payment_type_name','payment'],''),'amount'=>(float)val($p,['amount'],0),'tendered'=>(float)val($p,['tendered'],0),'change'=>(float)val($p,['change_amount','change'],0),'referenceNo'=>(string)val($p,['reference_no','reference'],''),'date'=>dt(val($p,['paid_at','created_at'])),'paid'=>true];$s['payment']=$s['payments'][0]['payment']??'';$s['paymentAmount']=array_sum(array_map(fn($x)=>(float)$x['amount'],$s['payments']));$s['paid']=strtoupper((string)$s['paymentStatus'])==='PAID'||$s['paymentAmount']>=$s['total'];return$s;}
function mapPurchase(PDO $pdo,array $r):array{$p=['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'no'=>(string)val($r,['purchase_no','number'],''),'number'=>(string)val($r,['purchase_no','number'],''),'externalDocument'=>(string)val($r,['external_document','external_doc'],''),'supplierId'=>(string)val($r,['supplier_id'],''),'date'=>dt(val($r,['purchase_date','created_at'])),'dueDate'=>dt(val($r,['due_date'])), 'stockDate'=>dt(val($r,['stock_date'])), 'subtotal'=>(float)val($r,['subtotal'],0),'discount'=>(float)val($r,['discount'],0),'tax'=>(float)val($r,['tax'],0),'total'=>(float)val($r,['total'],0),'status'=>(string)val($r,['status'],'Received'),'internalNote'=>(string)val($r,['notes','internal_note'],''),'note'=>(string)val($r,['notes'],''),'paid'=>((int)val($r,['paid'],1))!==0,'paymentType'=>(string)val($r,['payment_type','payment'],''),'paymentAmount'=>(float)val($r,['payment_amount','paid_amount','total'],0),'createdBy'=>val($r,['created_by'],''),'items'=>[]];foreach(childRows($pdo,'purchase_items','purchase_id',(int)$r['id']) as $i)$p['items'][]=['productId'=>(int)val($i,['product_id'],0),'productName'=>(string)val($i,['product_name','name'],''),'qty'=>(float)val($i,['quantity','qty'],0),'cost'=>(float)val($i,['cost_price','cost','unit_price','price'],0),'taxRate'=>(float)val($i,['tax_rate','tax'],0),'discount'=>(float)val($i,['discount','discount_amount'],0)];return$p;}
function mapOrder(PDO $pdo,array $r):array{$o=['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'name'=>(string)val($r,['order_name','name'],''),'number'=>(string)val($r,['order_number','number'],''),'date'=>dt(val($r,['order_date','created_at'])),'customerId'=>(string)val($r,['customer_id'],''),'discount'=>(float)val($r,['discount'],0),'taxRate'=>(float)val($r,['tax_rate'],0),'tax'=>(float)val($r,['tax'],0),'status'=>(string)val($r,['status'],'Open'),'comment'=>(string)val($r,['comment','notes'],''),'serviceType'=>(string)val($r,['service_type'],''),'table'=>(string)val($r,['table_name','table'],''),'total'=>(float)val($r,['total'],0),'items'=>[]];foreach(childRows($pdo,'open_order_items','open_order_id',(int)$r['id']) as $i)$o['items'][]=['productId'=>(int)val($i,['product_id'],0),'name'=>(string)val($i,['product_name','name'],''),'qty'=>(float)val($i,['quantity','qty'],0),'price'=>(float)val($i,['unit_price','price'],0),'id'=>(int)val($i,['product_id','id'])];return$o;}
function mapCash(array $r):array{return['id'=>(int)$r['id'],'date'=>dt(val($r,['movement_date','created_at'])), 'type'=>(string)val($r,['movement_type','type'],''),'amount'=>(float)val($r,['amount'],0),'reason'=>(string)val($r,['reason','notes'],''),'user'=>(string)val($r,['user_name','created_by'],''),'createdBy'=>val($r,['created_by'], '')];}
function mapStock(array $r):array{return['id'=>(int)$r['id'],'date'=>dt(val($r,['movement_date','created_at'])),'productId'=>(int)val($r,['product_id'],0),'productName'=>(string)val($r,['product_name','name'],''),'code'=>(string)val($r,['code','product_code'],''),'type'=>(string)val($r,['movement_type','type'],''),'change'=>(float)val($r,['quantity_change','quantity','change','qty'],0),'quantityAfter'=>(float)val($r,['quantity_after'],0),'reference'=>(string)val($r,['reference_no','reference'],''),'notes'=>(string)val($r,['notes','reason'],''),'createdBy'=>(string)val($r,['created_by'],'' )];}
function mapPaymentType(array $r):array{return['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'name'=>(string)val($r,['name'],''),'code'=>(string)val($r,['code'],''),'enabled'=>(bool)val($r,['enabled','active'],1),'active'=>(bool)val($r,['active','enabled'],1),'markPaid'=>(bool)val($r,['mark_paid'],true),'customerRequired'=>(bool)val($r,['customer_required'],false),'position'=>(int)val($r,['position','sort_order'],0),'quickPayment'=>(bool)val($r,['quick_payment'],false),'changeAllowed'=>(bool)val($r,['change_allowed'],false),'printReceipt'=>(bool)val($r,['print_receipt'],true),'shortcutKey'=>(string)val($r,['shortcut_key'],''),'openCashDrawer'=>(bool)val($r,['open_cash_drawer'],false)];}
function mapPromo(array $r):array{
 $days=val($r,['days_of_week'],[]); if(is_string($days)&&$days!==''){ $decoded=json_decode($days,true); if(is_array($decoded))$days=$decoded; }
 $items=val($r,['items','promotion_items','items_json'],[]); if(is_string($items)&&$items!==''){ $decoded=json_decode($items,true); if(is_array($decoded))$items=$decoded; }
 if(!is_array($days))$days=[]; if(!is_array($items))$items=[];
 return ['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'name'=>(string)val($r,['name','title'],''),'title'=>(string)val($r,['title','name'],''),'description'=>(string)val($r,['description'],''),'active'=>(bool)val($r,['active','enabled'],1),'enabled'=>(bool)val($r,['enabled','active'],1),'startDate'=>(string)val($r,['start_date'],''),'endDate'=>(string)val($r,['end_date'],''),'discountType'=>(string)val($r,['discount_type','type'],''),'type'=>(string)val($r,['type','discount_type'],''),'value'=>(float)val($r,['discount_value','value'],0),'discountValue'=>(float)val($r,['discount_value','value'],0),'daysOfWeek'=>$days,'items'=>$items,'notes'=>(string)val($r,['notes'],'')];
}
function mapSupplier(array $r):array{return['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'code'=>(string)val($r,['code','supplier_code'],''),'name'=>(string)val($r,['name','supplier_name'],''),'phone'=>(string)val($r,['phone','phone_number'],''),'email'=>(string)val($r,['email','email_address'],''),'address'=>(string)val($r,['address','supplier_address'],''),'taxNumber'=>(string)val($r,['tax_number','tax_no'],''),'active'=>(bool)val($r,['active','enabled'],1),'enabled'=>(bool)val($r,['enabled','active'],1)];}
function mapZReport(array $r):array{
 $payload=val($r,['report_json','report_data','data_json'],null); if(is_string($payload)&&$payload!==''){ $decoded=json_decode($payload,true); if(is_array($decoded))$payload=$decoded; } if(!is_array($payload))$payload=[];
 return ['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'number'=>(int)val($r,['report_number','z_number','number'],val($payload,['number'],0)),'date'=>dt(val($r,['business_date','closed_at','created_at','date'])),'user'=>(string)val($r,['user_name','created_by','user'],val($payload,['user'],'')),'total'=>(float)val($r,['total_sales','total'],val($payload,['total'],0)),'cashTotal'=>(float)val($r,['total_cash','cash_total'],val($payload,['cashTotal'],0)),'transactions'=>(int)val($r,['total_transactions','transactions'],val($payload,['transactions'],0)),'tenders'=>is_array(val($payload,['tenders'],[]))?val($payload,['tenders'],[]):[],'businessDate'=>(string)val($r,['business_date'],val($payload,['businessDate'],''))];
}
function readState(PDO $pdo,int $oid,string $k):array{
 $map=['sales'=>['t'=>'sales','f'=>fn($r)=>mapSale($pdo,$r)],'purchases'=>['t'=>'purchases','f'=>fn($r)=>mapPurchase($pdo,$r)],'orders'=>['t'=>'open_orders','f'=>fn($r)=>mapOrder($pdo,$r)],'cashMovements'=>['t'=>'cash_movements','f'=>fn($r)=>mapCash($r)],'stockHistory'=>['t'=>'stock_movements','f'=>fn($r)=>mapStock($r)],'paymentTypes'=>['t'=>'payment_types','f'=>fn($r)=>mapPaymentType($r)],'promos'=>['t'=>'promotions','f'=>fn($r)=>mapPromo($r)],'suppliers'=>['t'=>'suppliers','f'=>fn($r)=>mapSupplier($r)],'zReports'=>['t'=>'end_of_day','f'=>fn($r)=>mapZReport($r)]];
 if(!isset($map[$k]))throw new InvalidArgumentException('Unsupported relational state key: '.$k);$rs=rows($pdo,$map[$k]['t'],$oid);return array_map($map[$k]['f'],$rs);
}
try{$pdo=new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$oid=outletId($pdo,(string)($_GET['outlet_id']??'SP01'));$key=trim((string)($_GET['state_key']??''));if($key==='')throw new InvalidArgumentException('state_key is required.');$data=readState($pdo,$oid,$key);echo json_encode(['ok'=>true,'api_version'=>'V10','state_key'=>$key,'outlet_id'=>$oid,'count'=>count($data),'data'=>$data],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}catch(Throwable $e){http_response_code(500);echo json_encode(['ok'=>false,'api_version'=>'V10','error'=>$e->getMessage()],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
