<?php
declare(strict_types=1);
require_once __DIR__ . '/security.php';
header('Content-Type: application/json; charset=utf-8');
header('X-SP-Manager-DB-Version: V10');
if ($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
$config=require __DIR__.'/config.php';
$db=$config['db']??null;$host=(string)($db['host']??$config['db_host']??'localhost');$port=(string)($db['port']??$config['db_port']??'3306');$name=(string)($db['name']??$config['db_name']??'');$user=(string)($db['user']??$config['db_user']??'');$pass=(string)($db['pass']??$config['db_pass']??'');
function connectPdo(string $host,string $port,string $name,string $user,string $pass):PDO{
    $hosts=[$host];
    $normalized=strtolower(trim($host));
    if($normalized==='localhost')$hosts[]='127.0.0.1';
    elseif($normalized==='127.0.0.1')$hosts[]='localhost';
    $last=null;
    foreach(array_values(array_unique($hosts)) as $candidate){
        try{return new PDO("mysql:host={$candidate};port={$port};dbname={$name};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);}
        catch(Throwable $e){$last=$e;}
    }
    throw $last??new RuntimeException('Database connection failed.');
}
function cols(PDO $pdo,string $table):array{$q=$pdo->query('DESCRIBE `'.str_replace('`','``',$table).'`');$o=[];foreach($q->fetchAll() as $r){$o[(string)$r['Field']]=$r;}return $o;}
function tableExists(PDO $pdo,string $table):bool{$q=$pdo->prepare('SELECT COUNT(*) FROM information_schema.tables WHERE table_schema=DATABASE() AND table_name=?');$q->execute([$table]);return(int)$q->fetchColumn()>0;}
function val(array $r,array $keys,$default=null){foreach($keys as $k)if(array_key_exists($k,$r)&&$r[$k]!==null)return $r[$k];return $default;}
function dt($v){if($v===null||$v==='')return null;$t=strtotime(str_replace('T',' ',(string)$v));return $t===false?(string)$v:date('c',$t);}
function outletId(PDO $pdo,string $outlet):int{$outlet=trim($outlet?:'SP01');if(ctype_digit($outlet)){$q=$pdo->prepare('SELECT id FROM outlets WHERE id=? AND active=1 LIMIT 1');$q->execute([(int)$outlet]);}else{$q=$pdo->prepare('SELECT id FROM outlets WHERE outlet_code=? AND active=1 LIMIT 1');$q->execute([$outlet]);}$id=(int)($q->fetchColumn()?:0);if(!$id)throw new RuntimeException('Outlet not found: '.$outlet);return$id;}
function rows(PDO $pdo,string $table,int $oid):array{if(!tableExists($pdo,$table))return[];$s=cols($pdo,$table);$sql='SELECT * FROM `'.$table.'`';$args=[];if(isset($s['outlet_id'])){$sql.=' WHERE outlet_id=?';$args[]=$oid;}$sql.=' ORDER BY id ASC';$q=$pdo->prepare($sql);$q->execute($args);return$q->fetchAll();}
function childRows(PDO $pdo,string $table,string $fk,int $id):array{if(!tableExists($pdo,$table))throw new RuntimeException('Required detail table is missing: '.$table);$s=cols($pdo,$table);if(!isset($s[$fk]))throw new RuntimeException('Required detail column is missing: '.$table.'.'.$fk);$q=$pdo->prepare('SELECT * FROM `'.$table.'` WHERE `'.$fk.'`=? ORDER BY id ASC');$q->execute([$id]);return$q->fetchAll();}
function userLabel(PDO $pdo,$value):string{$id=(int)$value;if($id<=0)return(string)($value??'');if(!tableExists($pdo,'users'))return(string)$id;$schema=cols($pdo,'users');$fields=array_values(array_filter(['name','username'],fn($f)=>isset($schema[$f])));if(!$fields)return(string)$id;$q=$pdo->prepare('SELECT `'.implode('`,`',$fields).'` FROM users WHERE id=? LIMIT 1');$q->execute([$id]);$r=$q->fetch()?:[];foreach($fields as $f){$label=trim((string)($r[$f]??''));if($label!=='')return$label;}return(string)$id;}
function productLabel(PDO $pdo,int $productId):string{if($productId<=0||!tableExists($pdo,'products'))return'';$schema=cols($pdo,'products');$fields=array_values(array_filter(['product_name','name','sku','product_code'],fn($f)=>isset($schema[$f])));if(!$fields)return'';$q=$pdo->prepare('SELECT `'.implode('`,`',$fields).'` FROM products WHERE id=? LIMIT 1');$q->execute([$productId]);$r=$q->fetch()?:[];foreach(['product_name','name','sku','product_code'] as $f){$label=trim((string)($r[$f]??''));if($label!=='')return$label;}return'';}
function mapSale(PDO $pdo,array $r):array{$status=strtolower((string)val($r,['status'],''));$s=['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'no'=>(string)val($r,['sale_no','invoice_no','number'],''),'orderNumber'=>(string)val($r,['order_number','orderNumber'],''),'date'=>dt(val($r,['sale_date','created_at'])), 'customerId'=>(string)val($r,['customer_id'],''),'orderName'=>(string)val($r,['order_name'],''),'serviceType'=>(string)val($r,['service_type'],''),'subtotal'=>(float)val($r,['subtotal'],0),'discount'=>(float)val($r,['discount'],0),'tax'=>(float)val($r,['tax'],0),'total'=>(float)val($r,['total'],0),'paymentStatus'=>(string)val($r,['payment_status'],''),'status'=>(string)val($r,['status'],'COMPLETED'),'createdBy'=>userLabel($pdo,val($r,['created_by'],'')),'userName'=>userLabel($pdo,val($r,['created_by'],'')),'note'=>(string)val($r,['notes','note'],''),'internalNote'=>'','voided'=>strtolower((string)val($r,['voided'],0))==='1'||in_array($status,['void','voided'],true),'refunded'=>strtolower((string)val($r,['refunded'],0))==='1'||in_array($status,['refund','refunded'],true),'items'=>[],'payments'=>[]];foreach(childRows($pdo,'sale_items','sale_id',(int)$r['id']) as $i)$s['items'][]=['id'=>(int)val($i,['product_id','id']), 'productId'=>(int)val($i,['product_id'],0),'name'=>(string)val($i,['product_name','name'],''),'barcode'=>(string)val($i,['barcode'],''),'qty'=>(float)val($i,['quantity','qty'],0),'price'=>(float)val($i,['unit_price','price'],0),'discount'=>(float)val($i,['discount'],0),'tax'=>(float)val($i,['tax'],0),'total'=>(float)val($i,['line_total','total'],0),'warrantyEnabled'=>(bool)val($i,['warranty_enabled'],false),'warrantyYears'=>(int)val($i,['warranty_years'],0),'maintenanceEnabled'=>(bool)val($i,['maintenance_enabled'],false),'maintenanceCount'=>(int)val($i,['maintenance_count'],0)];foreach(childRows($pdo,'sale_payments','sale_id',(int)$r['id']) as $p)$s['payments'][]=['paymentTypeId'=>(int)val($p,['payment_type_id'],0),'payment'=>(string)val($p,['payment_type_name','payment'],''),'amount'=>(float)val($p,['amount'],0),'tendered'=>(float)val($p,['tendered'],0),'change'=>(float)val($p,['change_amount','change'],0),'referenceNo'=>(string)val($p,['reference_no','reference'],''),'date'=>dt(val($p,['paid_at','created_at'])),'paid'=>true];$s['payment']=$s['payments'][0]['payment']??'';$s['paymentAmount']=array_sum(array_map(fn($x)=>(float)$x['amount'],$s['payments']));$s['paid']=strtoupper((string)$s['paymentStatus'])==='PAID'||$s['paymentAmount']>=$s['total'];return$s;}
function mapPurchase(PDO $pdo,array $r):array{$meta=json_decode((string)val($r,['data_json'],''),true);if(!is_array($meta))$meta=[];$p=array_merge($meta,['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'no'=>(string)val($r,['purchase_no','number'],''),'number'=>(string)val($r,['purchase_no','number'],''),'supplierId'=>(string)val($r,['supplier_id'],val($meta,['supplierId','supplier_id'],'')),'date'=>dt(val($r,['purchase_date','created_at'])),'subtotal'=>(float)val($r,['subtotal'],val($meta,['subtotal'],0)),'discount'=>(float)val($r,['discount'],val($meta,['discount'],0)),'tax'=>(float)val($r,['tax'],val($meta,['tax'],0)),'total'=>(float)val($r,['total'],val($meta,['total'],0)),'status'=>(string)val($r,['status'],val($meta,['status'],'Received')),'internalNote'=>(string)val($r,['notes','internal_note'],val($meta,['internalNote','note'],'')),'note'=>(string)val($r,['notes'],val($meta,['note'],'')),'paid'=>((int)val($r,['paid'],val($meta,['paid'],1)))!==0,'paymentAmount'=>(float)val($r,['payment_amount','paid_amount'],val($meta,['paymentAmount','paid_amount'],val($r,['total'],0))),'createdBy'=>userLabel($pdo,val($r,['created_by'],val($meta,['createdBy'],'')))]);$p['items']=[];foreach(childRows($pdo,'purchase_items','purchase_id',(int)$r['id']) as $i){$itemMeta=json_decode((string)val($i,['data_json'],''),true);if(!is_array($itemMeta))$itemMeta=[];$productId=(int)val($i,['product_id'],val($itemMeta,['productId','product_id'],0));$name=(string)val($i,['product_name','name'],val($itemMeta,['productName','name'],''));if($name==='')$name=productLabel($pdo,$productId);$p['items'][]=array_merge($itemMeta,['productId'=>$productId,'productName'=>$name,'qty'=>(float)val($i,['quantity','qty'],val($itemMeta,['qty','quantity'],0)),'cost'=>(float)val($i,['unit_cost','cost_price','cost','unit_price','price'],val($itemMeta,['cost','costPrice'],0)),'taxRate'=>(float)val($i,['tax_rate','tax'],val($itemMeta,['taxRate','tax_rate'],0)),'discount'=>(float)val($i,['discount','discount_amount'],val($itemMeta,['discount'],0))]);}return$p;}
  function mapOrder(PDO $pdo,array $r):array{$meta=json_decode((string)val($r,['data_json'],''),true);if(!is_array($meta))$meta=[];$o=array_merge($meta,['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'name'=>(string)val($r,['order_name','name'],val($meta,['name','orderName'],'')),'number'=>(string)val($r,['order_no','order_number','number'],val($meta,['no','number','orderNumber'],'')),'date'=>dt(val($meta,['date','orderDate','order_date'],val($r,['created_at'],''))),'customerId'=>(string)val($r,['customer_id'],val($meta,['customerId','customer_id'],'')),'subtotal'=>(float)val($r,['subtotal'],val($meta,['subtotal'],0)),'discount'=>(float)val($r,['discount'],val($meta,['discount'],0)),'taxRate'=>(float)val($meta,['taxRate','tax_rate'],0),'tax'=>(float)val($r,['tax'],val($meta,['tax'],0)),'status'=>(string)val($r,['status'],val($meta,['status'],'Open')),'comment'=>(string)val($meta,['comment','notes'],''),'serviceType'=>(string)val($meta,['serviceType','service_type'],''),'table'=>(string)val($meta,['table','tableName','table_name'],''),'total'=>(float)val($r,['total'],val($meta,['total'],0))]);$o['items']=[];$metaItems=is_array($meta['items']??null)?$meta['items']:[];foreach(childRows($pdo,'open_order_items','open_order_id',(int)$r['id']) as $n=>$i){$itemMeta=is_array($metaItems[$n]??null)?$metaItems[$n]:[];$productId=(int)val($i,['product_id'],val($itemMeta,['productId','product_id'],0));$o['items'][]=array_merge($itemMeta,['productId'=>$productId,'name'=>(string)val($i,['product_name','name'],val($itemMeta,['name','productName'],'')),'qty'=>(float)val($i,['quantity','qty'],val($itemMeta,['qty','quantity'],0)),'price'=>(float)val($i,['unit_price','price'],val($itemMeta,['price','unitPrice'],0)),'discount'=>(float)val($i,['discount'],val($itemMeta,['discount'],0)),'tax'=>(float)val($i,['tax'],val($itemMeta,['tax'],0)),'total'=>(float)val($i,['line_total'],val($itemMeta,['total','lineTotal'],0)),'id'=>$productId]);}return$o;}
function mapCash(PDO $pdo,array $r):array{return['id'=>(int)$r['id'],'date'=>dt(val($r,['movement_date','created_at'])), 'type'=>(string)val($r,['movement_type','type'],''),'amount'=>(float)val($r,['amount'],0),'reason'=>(string)val($r,['reason','notes'],''),'user'=>userLabel($pdo,val($r,['user_name','created_by'],'')),'createdBy'=>val($r,['created_by'], '')];}
  function mapStock(PDO $pdo,array $r):array{$productId=(int)val($r,['product_id'],0);$name=(string)val($r,['product_name','name'],'');if($name==='')$name=productLabel($pdo,$productId);$ref=(string)val($r,['reference_no','reference'],'');if($ref===''&&val($r,['reference_type'],'' )!=='')$ref=(string)val($r,['reference_type'],'').((int)val($r,['reference_id'],0)>0?' #'.(int)val($r,['reference_id'],0):'');return['id'=>(int)$r['id'],'date'=>dt(val($r,['movement_date','created_at'])),'productId'=>$productId,'productName'=>$name,'code'=>(string)val($r,['code','product_code'],''),'type'=>(string)val($r,['movement_type','type'],''),'change'=>(float)val($r,['quantity_change','quantity','change','qty'],0),'stockBefore'=>(float)val($r,['stock_before'],0),'quantityAfter'=>(float)val($r,['quantity_after','stock_after'],0),'unitCost'=>(float)val($r,['unit_cost'],0),'reference'=>$ref,'notes'=>(string)val($r,['notes','reason'],''),'createdBy'=>userLabel($pdo,val($r,['created_by'],''))];}
function mapPaymentType(array $r):array{return['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'name'=>(string)val($r,['payment_name','name'],''),'code'=>(string)val($r,['payment_code','code'],''),'enabled'=>(bool)val($r,['enabled','active'],1),'active'=>(bool)val($r,['enabled','active'],1),'markPaid'=>(bool)val($r,['mark_paid'],true),'customerRequired'=>(bool)val($r,['customer_required'],false),'position'=>(int)val($r,['sort_order','position'],0),'quickPayment'=>(bool)val($r,['quick_payment'],false),'changeAllowed'=>(bool)val($r,['change_allowed'],false),'printReceipt'=>(bool)val($r,['print_receipt'],true),'shortcutKey'=>(string)val($r,['shortcut_key'],''),'openCashDrawer'=>(bool)val($r,['open_cash_drawer'],false)];}
function mapPromo(array $r):array{
 $payload=val($r,['data_json'],null);
 if(is_string($payload)&&$payload!==''){ $decoded=json_decode($payload,true); if(is_array($decoded))$payload=$decoded; }
 if(!is_array($payload))$payload=[];
 $days=val($payload,['daysOfWeek','days_of_week'],val($r,['days_of_week'],[]));
 $items=val($payload,['items','promotion_items','items_json'],val($r,['items','promotion_items','items_json'],[]));
 if(is_string($days)&&$days!==''){ $decoded=json_decode($days,true); if(is_array($decoded))$days=$decoded; }
 if(is_string($items)&&$items!==''){ $decoded=json_decode($items,true); if(is_array($decoded))$items=$decoded; }
 if(!is_array($days))$days=[]; if(!is_array($items))$items=[];
 $startAt=(string)val($r,['start_at'],val($payload,['startAt','start_date'],''));
 $endAt=(string)val($r,['end_at'],val($payload,['endAt','end_date'],''));
 $startDate=$startAt?substr($startAt,0,10):(string)val($payload,['startDate','start_date'],'');
 $endDate=$endAt?substr($endAt,0,10):(string)val($payload,['endDate','end_date'],'');
 $startTime=strlen($startAt)>=16?substr($startAt,11,5):(string)val($payload,['startTime','start_time'],'');
 $endTime=strlen($endAt)>=16?substr($endAt,11,5):(string)val($payload,['endTime','end_time'],'');
 $value=(float)val($payload,['value','discountValue','discount_value'],val($r,['discount_percent'],0));
 return ['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'name'=>(string)val($r,['promotion_name'],val($payload,['name','promotionName','title'],'')),'title'=>(string)val($payload,['title','name','promotionName'],val($r,['promotion_name'],'')),'description'=>(string)val($payload,['description'],''),'active'=>(bool)val($r,['active'],1),'enabled'=>(bool)val($r,['active'],1),'startDate'=>$startDate,'startTime'=>$startTime,'endDate'=>$endDate,'endTime'=>$endTime,'discountType'=>(string)val($payload,['discountType','type'],''),'type'=>(string)val($payload,['type','discountType'],''),'value'=>$value,'discountValue'=>$value,'daysOfWeek'=>$days,'items'=>$items,'notes'=>(string)val($payload,['notes'],''), 'price'=>(float)val($r,['price'],0)];
}
function mapSupplier(array $r):array{$meta=json_decode((string)val($r,['metadata_json'],''),true);if(!is_array($meta))$meta=[];return array_merge($meta,['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'code'=>(string)val($r,['code','supplier_code'],val($meta,['code','supplierCode'],'')),'name'=>(string)val($r,['name','supplier_name'],val($meta,['name','supplierName'],'')),'phone'=>(string)val($r,['phone','phone_number'],val($meta,['phone','phoneNumber'],'')),'email'=>(string)val($r,['email','email_address'],val($meta,['email','emailAddress'],'')),'address'=>(string)val($r,['address','supplier_address'],val($meta,['address','supplierAddress'],'')),'taxNumber'=>(string)val($r,['tax_number','tax_no'],val($meta,['taxNumber','tax_number'],'')),'active'=>(bool)val($r,['active','enabled'],val($meta,['active','enabled'],1)),'enabled'=>(bool)val($r,['enabled','active'],val($meta,['enabled','active'],1))]);}
function mapZReport(array $r):array{
 $payload=val($r,['report_json','report_data','data_json'],null); if(is_string($payload)&&$payload!==''){ $decoded=json_decode($payload,true); if(is_array($decoded))$payload=$decoded; } if(!is_array($payload))$payload=[];
 return ['id'=>(int)$r['id'],'dbId'=>(int)$r['id'],'number'=>(int)val($r,['report_number','z_number','number'],val($payload,['number'],0)),'date'=>dt(val($r,['business_date','closed_at','created_at','date'])),'user'=>(string)val($r,['user_name','created_by','user'],val($payload,['user'],'')),'total'=>(float)val($r,['total_sales','total'],val($payload,['total'],0)),'cashTotal'=>(float)val($r,['total_cash','cash_total'],val($payload,['cashTotal'],0)),'transactions'=>(int)val($r,['total_transactions','transactions'],val($payload,['transactions'],0)),'tenders'=>is_array(val($payload,['tenders'],[]))?val($payload,['tenders'],[]):[],'businessDate'=>(string)val($r,['business_date'],val($payload,['businessDate'],''))];
}
function readState(PDO $pdo,int $oid,string $k):array{
 $map=['sales'=>['t'=>'sales','f'=>fn($r)=>mapSale($pdo,$r)],'purchases'=>['t'=>'purchases','f'=>fn($r)=>mapPurchase($pdo,$r)],'orders'=>['t'=>'open_orders','f'=>fn($r)=>mapOrder($pdo,$r)],'cashMovements'=>['t'=>'cash_movements','f'=>fn($r)=>mapCash($pdo,$r)],'stockHistory'=>['t'=>'stock_movements','f'=>fn($r)=>mapStock($pdo,$r)],'paymentTypes'=>['t'=>'payment_types','f'=>fn($r)=>mapPaymentType($r)],'promos'=>['t'=>'promotions','f'=>fn($r)=>mapPromo($r)],'suppliers'=>['t'=>'suppliers','f'=>fn($r)=>mapSupplier($r)],'zReports'=>['t'=>'end_of_day','f'=>fn($r)=>mapZReport($r)]];
 if($k==='zReports')spEnsureEndOfDayMetadata($pdo);if($k==='purchases')spEnsurePurchaseMetadata($pdo);if($k==='suppliers')spEnsureSupplierMetadata($pdo);
 if(!isset($map[$k]))throw new InvalidArgumentException('Unsupported relational state key: '.$k);if(!tableExists($pdo,$map[$k]['t']))throw new RuntimeException('Required database table is missing: '.$map[$k]['t'].'. Apply the SP-Manager database schema before reading this data.');$parentCols=cols($pdo,$map[$k]['t']);if(in_array($k,['sales','purchases','orders','cashMovements','stockHistory','zReports'],true)&&!isset($parentCols['outlet_id']))throw new RuntimeException('Required outlet_id column is missing from '.$map[$k]['t'].'. Refusing to expose unscoped outlet data.');$requiredChildren=match($k){'sales'=>['sale_items','sale_payments'],'purchases'=>['purchase_items'],'orders'=>['open_order_items'],default=>[]};foreach($requiredChildren as $child)if(!tableExists($pdo,$child))throw new RuntimeException('Required detail table is missing: '.$child.'. Apply the SP-Manager database schema before reading this data.');$rs=rows($pdo,$map[$k]['t'],$oid);return array_map($map[$k]['f'],$rs);
}
try{$pdo=spApiDatabase();$oid=outletId($pdo,(string)($_GET['outlet_id']??'SP01'));$key=trim((string)($_GET['state_key']??''));if($key==='')throw new InvalidArgumentException('state_key is required.');$data=readState($pdo,$oid,$key);echo json_encode(['ok'=>true,'api_version'=>'V10','state_key'=>$key,'outlet_id'=>$oid,'count'=>count($data),'data'=>$data],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}catch(Throwable $e){http_response_code(500);echo json_encode(['ok'=>false,'api_version'=>'V10','error'=>$e->getMessage()],JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);}
