<?php
declare(strict_types=1);
header('Content-Type: application/json; charset=utf-8');header('Access-Control-Allow-Origin: *');header('Access-Control-Allow-Headers: Content-Type');header('Access-Control-Allow-Methods: GET, POST, OPTIONS');if($_SERVER['REQUEST_METHOD']==='OPTIONS'){http_response_code(204);exit;}
$config=require __DIR__.'/config.php';$db=$config['db']??null;$host=(string)($db['host']??$config['db_host']??'localhost');$port=(string)($db['port']??$config['db_port']??'3306');$name=(string)($db['name']??$config['db_name']??'');$user=(string)($db['user']??$config['db_user']??'');$pass=(string)($db['pass']??$config['db_pass']??'');
function body():array{$v=json_decode(file_get_contents('php://input')?:'',true);return is_array($v)?$v:[];}function out(array $v,int $s=200):never{http_response_code($s);echo json_encode($v,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE);exit;}function outlet(PDO $pdo,mixed $v):int{$v=trim((string)($v??'SP01'));if($v==='' )$v='SP01';if(ctype_digit($v))return(int)$v;$q=$pdo->prepare('SELECT id FROM outlets WHERE outlet_code=? AND active=1 LIMIT 1');$q->execute([$v]);$id=(int)($q->fetchColumn()?:0);if($id<=0)throw new InvalidArgumentException('Outlet not found.');return$id;}
function setting(PDO $pdo,int $oid,string $group,string $key,mixed $value):void{$q=$pdo->prepare('INSERT INTO outlet_settings(outlet_id,setting_group,setting_key,setting_value) VALUES(?,?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value)');$q->execute([$oid,$group,$key,json_encode($value,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);}function readSetting(PDO $pdo,int $oid,string $group,string $key,mixed $fallback=null):mixed{$q=$pdo->prepare('SELECT setting_value FROM outlet_settings WHERE outlet_id=? AND setting_group=? AND setting_key=? LIMIT 1');$q->execute([$oid,$group,$key]);$v=$q->fetchColumn();if($v===false)return$fallback;$d=json_decode((string)$v,true);return json_last_error()===JSON_ERROR_NONE?$d:$v;}
function company(PDO $pdo,int $oid):array{$q=$pdo->prepare('SELECT * FROM company_settings WHERE outlet_id=? LIMIT 1');$q->execute([$oid]);$r=$q->fetch();if(!$r)return[];$meta=json_decode((string)($r['metadata_json']??''),true);$meta=is_array($meta)?$meta:[];return array_merge(['name'=>$r['company_name']??'Shining Pearl Tinted','registrationNo'=>$r['registration_no']??'','taxNumber'=>$r['tax_number']??'','phoneNumber'=>$r['phone_number']??'','email'=>$r['email']??'','website'=>$r['website']??'','streetName'=>$r['street_name']??'','buildingNumber'=>$r['building_number']??'','additionalStreetName'=>$r['additional_street_name']??'','plotIdentification'=>$r['plot_identification']??'','district'=>$r['district']??'','postalCode'=>$r['postal_code']??'','city'=>$r['city']??'','state'=>$r['state']??'','country'=>$r['country']??'Malaysia','logo'=>$r['logo_url']??'','currencyCode'=>$r['currency_code']??'MYR','currencySymbol'=>$r['currency_symbol']??'RM'],$meta);}
function saveCompany(PDO $pdo,int $oid,array $c):void{$meta=$c;foreach(['name','registrationNo','taxNumber','phoneNumber','email','website','streetName','buildingNumber','additionalStreetName','plotIdentification','district','postalCode','city','state','country','logo','currencyCode','currencySymbol'] as $k)unset($meta[$k]);$sql='INSERT INTO company_settings(outlet_id,company_name,registration_no,tax_number,phone_number,email,website,street_name,building_number,additional_street_name,plot_identification,district,postal_code,city,state,country,logo_url,currency_code,currency_symbol,metadata_json) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON DUPLICATE KEY UPDATE company_name=VALUES(company_name),registration_no=VALUES(registration_no),tax_number=VALUES(tax_number),phone_number=VALUES(phone_number),email=VALUES(email),website=VALUES(website),street_name=VALUES(street_name),building_number=VALUES(building_number),additional_street_name=VALUES(additional_street_name),plot_identification=VALUES(plot_identification),district=VALUES(district),postal_code=VALUES(postal_code),city=VALUES(city),state=VALUES(state),country=VALUES(country),logo_url=VALUES(logo_url),currency_code=VALUES(currency_code),currency_symbol=VALUES(currency_symbol),metadata_json=VALUES(metadata_json)';$q=$pdo->prepare($sql);$q->execute([$oid,$c['name']??'Shining Pearl Tinted',$c['registrationNo']??null,$c['taxNumber']??null,$c['phoneNumber']??null,$c['email']??null,$c['website']??null,$c['streetName']??null,$c['buildingNumber']??null,$c['additionalStreetName']??null,$c['plotIdentification']??null,$c['district']??null,$c['postalCode']??null,$c['city']??null,$c['state']??null,$c['country']??'Malaysia',$c['logo']??null,$c['currencyCode']??'MYR',$c['currencySymbol']??'RM',json_encode($meta,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE)]);}
try{$pdo=new PDO("mysql:host={$host};port={$port};dbname={$name};charset=utf8mb4",$user,$pass,[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);$oid=outlet($pdo,$_GET['outlet_id']??$_POST['outlet_id']??'SP01');$action=strtolower(trim((string)($_GET['action']??$_POST['action']??'')));if($action==='health')out(['ok'=>true,'service'=>'SP-Manager settings API','outletId'=>$oid]);
if($action==='all'&&$_SERVER['REQUEST_METHOD']==='GET'){out(['ok'=>true,'settings'=>readSetting($pdo,$oid,'SP-MANAGER','settings',null),'company'=>company($pdo,$oid),'businessDay'=>readSetting($pdo,$oid,'SP-MANAGER','businessDay',null),'taxRate'=>readSetting($pdo,$oid,'SP-MANAGER','taxRate',null),'customerDisplayTerminal'=>readSetting($pdo,$oid,'SP-MANAGER','customerDisplayTerminal',null)]);}
if($action==='save'&&$_SERVER['REQUEST_METHOD']==='POST'){ $b=body();$pdo->beginTransaction();if(array_key_exists('settings',$b))setting($pdo,$oid,'SP-MANAGER','settings',$b['settings']);if(array_key_exists('businessDay',$b))setting($pdo,$oid,'SP-MANAGER','businessDay',$b['businessDay']);if(array_key_exists('taxRate',$b))setting($pdo,$oid,'SP-MANAGER','taxRate',$b['taxRate']);if(array_key_exists('customerDisplayTerminal',$b))setting($pdo,$oid,'SP-MANAGER','customerDisplayTerminal',$b['customerDisplayTerminal']);if(is_array($b['company']??null))saveCompany($pdo,$oid,$b['company']);$pdo->commit();out(['ok'=>true]);}
if($action==='company'&&$_SERVER['REQUEST_METHOD']==='POST'){ $b=body(); saveCompany($pdo,$oid,is_array(($b['company']??null))?$b['company']:$b); out(['ok'=>true,'company'=>company($pdo,$oid)]);}
if($action==='setting'&&$_SERVER['REQUEST_METHOD']==='POST'){ $b=body();$key=trim((string)($b['key']??''));if($key==='')throw new InvalidArgumentException('Setting key is required.');setting($pdo,$oid,'SP-MANAGER',$key,$b['value']??null);out(['ok'=>true]);}
throw new InvalidArgumentException('Unknown action.');}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();out(['ok'=>false,'error'=>$e->getMessage()],500);}
